### ISSUE TITLE
Cannot read property 'Aspect' of undefined

### ISSUE THREAD

**Issue by avalond** [lwansbrough/react-native-camera#1017]
in ios i use react-native-camera have this error 'Cannot read property 'Aspect' of undefined'

**Comment by TheBnl** [comment]
I have the same issue, the issue is triggered when the native module gets required. 
When simulating on iOS 10 the camera works just fine. 
Maybe the iOS camera API changed for iOS 11?

**Comment by avalond** [comment]
@TheBnl  in my all devices is not working, ios 9.3.3 ios 11.2,ios 11.1.3

**Comment by jonathanleahy** [comment]
Broken when I publish to android as well.

**Comment by sibelius** [comment]
use

`react-native link react-native-camera` and build again

**Comment by avalond** [comment]
@sibelius  not working, i try rm -rf node_model/   reinstall  and relink react-native-camera is not working in ios, please check

**Comment by sibelius** [comment]
Can you log all your NativeModules?

And check if there is a RCTCamera on it?

If there is no RCTCamera the link is wrong

Sometimes React-Native link does not work well

**Comment by jonathanleahy** [comment]
I tried with publishing to three phones. 2 more modern phones worked fine, the other came up with that error. Same project for all. The one which didn’t work was running android 5.1

**Comment by avalond** [comment]
this is my error page 
![42e94678-1468-4e97-ac93-19145dcc11ef](https://user-images.githubusercontent.com/5616958/33806381-5f881ef8-de02-11e7-9e31-1783c103d861.png)

this is my js code import react native camera
![73763c1c-e223-4a40-807b-c1be33b44843](https://user-images.githubusercontent.com/5616958/33806394-7b08e6e4-de02-11e7-8953-ec8b1b04febc.png)

this is my xcode link RCTCamera is working 
![3ed07fc5-5848-47ba-8d96-dc96ae1e5ca7](https://user-images.githubusercontent.com/5616958/33806400-8dd4e41c-de02-11e7-8f6c-a44bba607b45.png)

but is not working @sibelius

**Comment by sibelius** [comment]
Add this snippet to your code

```jsx
import { NativeModules } from 'react-native'

console.log('NativeModules: ', NativeModules);
```

you should have one of this 2

NativeModules.CameraManager || NativeModules.CameraModule;

a CameraManager for ios and a CameraModule for android

**Comment by avalond** [comment]
have this messages ExceptionsManager.js:73 Unhandled JS Exception: Cannot read property 'Aspect' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:73
logToConsole @ RCTLog.js:48
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:302
(anonymous) @ MessageQueue.js:116
__guard @ MessageQueue.js:265
callFunctionReturnFlushedQueue @ MessageQueue.js:115
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:73 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

@sibelius

**Comment by sibelius** [comment]
add this snippet before everything on your App.js

you can stop importing react-native-camera to help your debug

**Comment by avalond** [comment]
<img width="1165" alt="qq20171210-235754 2x" src="https://user-images.githubusercontent.com/5616958/33806619-fa18aa20-de05-11e7-9169-a4661a7c10d9.png">
i got log bug is not have Aspect

**Comment by sibelius** [comment]
you do not have Camera modules on your NativeModules

it is not linked properly

try in a clean project

**Comment by st4allen** [comment]
I also have this issue. Then I find that I missed two steps in the documentation.

First remember to add permissions in plist file.

```
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>
<key>NSMicrophoneUsageDescription</key>
```
Then remember to add dependency in your podfile.

`pod 'react-native-camera', :path => '../node_modules/react-native-camera'`
and run `pod install`.

For me it works after these two steps. If it still not work, check if you link the library properly.

Hope it helps.

**Comment by mashwinprdxn** [comment]
In case anyone's facing this issue on Android, please try the [gradle upgrade guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md). It worked for me.

**Comment by sadeghhosseini** [comment]
I am facing the same issue, would you please provide a react-native-camera demo app so that beginners can build their project on top of it?
