### ISSUE TITLE
App Crashed if don't have Camera permission 

### ISSUE THREAD

**Issue by Symous** [lwansbrough/react-native-camera#1026]
Hi,I have found out that the app will crash when the we try to open a page taht integer react-native-camera if the app doesn't have the permission of camera in iOS physical device. but it didn't happened on iOS simulator or Android Platform.

**Comment by sibelius** [comment]
check this https://github.com/lwansbrough/react-native-camera#ios-cameracheckdeviceauthorizationstatus-promise

**Comment by erez-guesty** [comment]
@sibelius 
the link is leading to the react-native-camera homepage...
where is the solution?
