### ISSUE TITLE
Device heats up

### ISSUE THREAD

**Issue by tronin** [lwansbrough/react-native-camera#103]
Hi, thanks for great component.

Is there a way to turn off the camera during transfer to another route? While working in the background, the device gets too hot.

Thanks.

**Comment by lwansbrough** [comment]
I'm going to implement a fix later today that stops the camera session when it's removed from its containing view. Perhaps the solution for you then would be to remove the camera from the view when it's not being viewed.

**Comment by darkrishabh** [comment]
@nashpro 
you can use the navigator didFocus listeners to activate and deactivate the camera.

On moving to the next route you can change the state and hide the camera, and on coming back use the didFocus listener to bring it back.

**Comment by lwansbrough** [comment]
Can you verify that this is still an issue with the latest version?

**Comment by nashpro** [comment]
iphone is still heated, we used willFocus to fix this problem.

**Comment by liubin915249126** [comment]
> iphone is still heated, we used willFocus to fix this problem.

i wanna to know how to use willFocus to fix this problem. tks a lot.
