### ISSUE TITLE
[Question]Photo taken notification

### ISSUE THREAD

**Issue by uikolas** [lwansbrough/react-native-camera#1033]
Maybe somebody has solution, how to show notification for user, when photo was taken?
I was thinking, about putting black screen for 100 milliseconds, when user presses camera button and then hide it. But is it a good solution?

**Comment by sibelius** [comment]
```jsx
const f = async () => {
  const one = await this.camera.capture();

   showNotification()
}
```

**Comment by uikolas** [comment]
Yes, i know that. But my question was, what great solution i can use for showing notification? Showing and alert after photo was taken?

**Comment by sibelius** [comment]
this is better on stackoverflow
