### ISSUE TITLE
Build failed after upgrading to React Native v0.51.0

### ISSUE THREAD

**Issue by ikhsanalatsary** [lwansbrough/react-native-camera#1037]
This problem after upgrading my project dependencies to react-native v0.51.0, react v16.0.0, react-native-camera v0.12.0 & try building iOS in Xcode v8.2.1. Screenshots:

![screen shot 2017-12-12 at 8 58 14 pm](https://user-images.githubusercontent.com/5897415/33888335-51db5db4-df7f-11e7-8c52-8db749821c15.png)

how to resolve this problem? 

Thank you

**Comment by sibelius** [comment]
check the breaking changes section of rn51

**Comment by ikhsanalatsary** [comment]
Consider negative border radii and widths invalid (99d294b) - @rsnara

![screen shot 2017-12-12 at 9 08 20 pm](https://user-images.githubusercontent.com/5897415/33888781-a616b800-df80-11e7-9748-996f7f7e8568.png)

**Comment by ikhsanalatsary** [comment]
@sibelius apparently, the problem occurs from cocoapods. Before I upgrade RN version to v0.51. I did unlink react-native-camera & linking again but I don't know it linked to pods. So i remove it from pods and linking to my *.xcodeproj.

**Comment by sibelius** [comment]
Great to hear that
