### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by amccloud** [lwansbrough/react-native-camera#105]
Why was podspec removed?

Even facebook distributes modules with a podspec https://github.com/facebook/react-native-fbsdk/tree/master/react-native-fbsdkcore

**Comment by lwansbrough** [comment]
It was never actually registered, and I'm hoping the React Native community can move to something better. Though I haven't had the time to work on that better solution. I think REM is currently the best attempt at bringing something better to the table (podspec solves iOS, but leaves Android unsolved.)
