### ISSUE TITLE
RCTBridge.h file not found

### ISSUE THREAD

**Issue by spierckel** [lwansbrough/react-native-camera#106]
Hello,

I followed your getting started but I have an error when building the application.
The import "RCTBridge.h" can't be found in the file RCTCamera.m.

Have you any idea to solve this problem ?

Another question, can we use this library for android ?

Thanks in advance,
Florian

**Comment by spierckel** [comment]
It was an error from me, I hadn't clone this library in the node_modules of the project folder but in another location so it wasn't working.

**Comment by AlisonWonderlandApps** [comment]
I get this error constantly. GRRRR
