### ISSUE TITLE
PropTypes should be imported from "prop-types"

### ISSUE THREAD

**Issue by husny-ahamed** [lwansbrough/react-native-camera#1061]
In react 16, we cannot import PropTypes from 'react', It shows an error in propTypes. We should import it like below
import PropTypes from "prop-types";
Please update your library index.js file. 

Thanks

**Comment by jgcmarins** [comment]
Hi, @husny-ahamed.
PRs are welcome 😄

**Comment by sibelius** [comment]
this is done already https://github.com/lwansbrough/react-native-camera/blob/master/index.js#L2
