### ISSUE TITLE
Added this to ReactNativeModules.com

### ISSUE THREAD

**Issue by wootwoot1234** [lwansbrough/react-native-camera#11]
I put together http://reactnativemodules.com last night and added your module.  It's a community run list of react native modules.  Hopefully it will make finding projects like these easier.  Am I missing any that you know of?

**Comment by lwansbrough** [comment]
https://github.com/ericvicenti/react-native-community - You should make that site read from a JSON list than can be updated via pull requests on GitHub! :+1:

**Comment by wootwoot1234** [comment]
Sure!  Send me a link to the json file.  You can also create an account and add the modules there.  I'd be happy to make you or @ericvicenti admin.
