### ISSUE TITLE
Taking cropped photo

### ISSUE THREAD

**Issue by vinu123** [lwansbrough/react-native-camera#119]
I want my camera view to be of square size i.e. half of my iPhone's screen. I tried using 'Aspect' => 'fit' however that is only for the camera view and not the actual picture. How can I restrict the picture to be my camera view's size?

**Comment by lwansbrough** [comment]
The camera doesn't support this and generally I'd like to keep it out of the camera. Processing should be left to a post-processing module.

**Comment by lwansbrough** [comment]
Take a look at `ImageEditingManager` that ships with React Native.

**Comment by vinu123** [comment]
Hey @lwansbrough, How can I use ImageEditingManager?

**Comment by achang28** [comment]
@vinu123 :  https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ImageEditingExample.js

**Comment by vinu123** [comment]
What I don't understand is that do I use <SquareImageCropper /> because this example exports that but when I do use it, I get an error. I just don't know how to use it. God, I feel so dumb :(

**Comment by jhack32** [comment]
If you'd like the camera to take the same image size as an iPhone camera. Check the link below. You'd need to adjust your preview to be the same as the iPhone camera.

https://github.com/cortlandtlabs/react-native-camera/pull/1
