### ISSUE TITLE
Force Fullscreen / On Top

### ISSUE THREAD

**Issue by cancan101** [lwansbrough/react-native-camera#120]
I am on IOS and I am using `NavigatorIOS` and the `TabBarIOS` and I would like the `Camera` component to occupy the full screen:
![image](https://cloud.githubusercontent.com/assets/51059/11047429/53522490-8700-11e5-8191-dff85c5ca203.png)

Is there any way to accomplish this?

**Comment by lwansbrough** [comment]
`<Modal/>` maybe. This problem isn't specific to the camera other than you're showing a camera in that view. Try the Reactiflux channel on Discord for help with this.

**Comment by YvesPhilippot** [comment]
I achieve this by using Portal component from react-native-paper
