### ISSUE TITLE
How do you get filetype of image?

### ISSUE THREAD

**Issue by sslash** [lwansbrough/react-native-camera#122]
Probably a simple question. But say I want to upload the image to a server. I use https://github.com/kamilkp/react-native-file-transfer to upload an image read from disk. However, how do you get the file type of the image? currently I do filename.match(/ext=(\S+)$/) but that stinks.

**Comment by lwansbrough** [comment]
It's always a jpeg.

**Comment by sslash** [comment]
nice. thanks
