### ISSUE TITLE
Resizing?

### ISSUE THREAD

**Issue by zackify** [lwansbrough/react-native-camera#128]
Is there a way to resize photos to be smaller? I'm uploading them with https://github.com/kamilkp/react-native-file-transfer

**Comment by lwansbrough** [comment]
Should be possible via `ImageEditingManager`. https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ImageEditingExample.js

**Comment by zackify** [comment]
Thanks a lot!

**Comment by zackify** [comment]
@lwansbrough I just made this: https://github.com/CodeFoundation/rn-resize might be good to add to the readme. Sure many people want to do this.
