### ISSUE TITLE
Check permissions to access Camera

### ISSUE THREAD

**Issue by bpeters** [lwansbrough/react-native-camera#134]
If a user denies permissions for the camera and then tries to access the camera the app will crash. Is there a way to check for camera permissions from the Camera Api? I can then request permission with an alert like the default.

**Comment by lwansbrough** [comment]
Apparently I forgot to expose the `checkDeviceAuthorizationStatus` via the JS API. You can do what you're asking via:

```javascript
NativeModules.CameraManager.checkDeviceAuthorizationStatus((function(err, isAuthorized) {}
```

I'd accept a PR if you want to expose that method on the `Camera` reference like others have been in the `index.ios.js` file.

**Comment by tonmanayo** [comment]
Hi, I'd like to know if there is any way of checking Camera permissions. I'd like to being up a modal before asking the users on IOS for permissions
