### ISSUE TITLE
Capture Reduced Resolution Photos

### ISSUE THREAD

**Issue by geirman** [lwansbrough/react-native-camera#153]
Firstly, great job! This is a great module. Doesn't look like it supports taking reduced resolution photos though unless I've missed something. Do you plan to support this or know of any work arounds?

FYI: For reference, NativeScript supports this 
[Taking a memory efficient picture](http://docs.nativescript.org/hardware/camera#taking-a-memory-efficient-picture)

**Comment by lwansbrough** [comment]
Typically I've recommended `ImageEditingManager`: https://github.com/lwansbrough/react-native-camera/issues/119

**Comment by charpeni** [comment]
I'll close this issue since it was introduced by #469, if you think it should still be opened let us know.
