### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by JakeRawr** [lwansbrough/react-native-camera#156]
Currently, the master branch has a fix for Tap to Focus crashing issue. But v0.3.8 doesn't have that fix.When will the next version be released? 

Thanks
-Jake

**Comment by dangnelson** [comment]
Also, with the new Android support, will there be a new release?

**Comment by lwansbrough** [comment]
Please pull the latest changes from master. There should be some much needed fixes in there.

**Comment by lwansbrough** [comment]
I'll be pushing for `1.0.0` once APIs and functionality has stabilized.

**Comment by viscasillas** [comment]
How does this Android support work? Can I use my existing code from iOS on Android?

**Comment by lwansbrough** [comment]
Eventually the APIs will all work the same, for now you may have to make conditional assignments on the camera props because of lack of support of some features.

**Comment by pocesar** [comment]
what the `next` branch is missing and/or update from 0.6?

**Comment by sibelius** [comment]
we gonna work on the next release here https://github.com/lwansbrough/react-native-camera/issues/246#issuecomment-350577509

I think using cameraview from google would help maintaing android
