### ISSUE TITLE
Linking does not seem to work

### ISSUE THREAD

**Issue by Mo-k-tec** [lwansbrough/react-native-camera#164]
I followed all steps but when i build the android app i get the following error.

    A problem occurred configuring project ':app'.
    > Cannot evaluate module react-native-camera : Configuration with name 'default' not found.

I added in the told files

    new RCTCameraPackage()
 
    include ':react-native-camera'
    project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera/android')

    dependencies {
      compile project(':react-native-camera')
      compile fileTree(dir: "libs", include: ["*.jar"])
      compile "com.android.support:appcompat-v7:23.0.1"
      compile "com.facebook.react:react-native:0.18.+"
    }

Any ideas?

Regards,
Mo

**Comment by dangnelson** [comment]
I'm having the same problem. 

I also don't see how to "Modify the ReactInstanceManager.builder() calls chain in android/app/main/java/.../MainActivity.java to include:" 

I don't have any references in my MainActivity.java file to ReactInstanceManager.

My path to MainActivity.java is also different:
    android/app/src/main/java/com/.../MainActivity.java

I running the latest version of RN.

**Comment by dangnelson** [comment]
This issue is related to React-Native 0.18. Here's a related solution:
https://github.com/marcshilling/react-native-image-picker/issues/74

I'll try to get a working version from that.

**Comment by dangnelson** [comment]
Tagging @farmisen since he was the original source for the documentation.

**Comment by rpopovici** [comment]
I linked this project with "git+https://github.com/lwansbrough/react-native-camera.git" in package.json instead of using npm version ^0.3.8 and it works this way
It looks like the npm repository was not update to the latest version

**Comment by ardowz** [comment]
In MainActivity.java

add this line:
import com.lwansbrough.RCTCamera.RCTCameraPackage;

before the class, that should do the trick.

**Comment by dangnelson** [comment]
Worked. Thanks @ardowz 

Here's what my final MainActivity looks like:

    package com.myapp;
    
    import com.facebook.react.ReactActivity;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    
    import com.lwansbrough.RCTCamera.RCTCameraPackage; // IMPORT
    import java.util.Arrays;
    import java.util.List;
    
    public class MainActivity extends ReactActivity {
    
        /**
         * Returns the name of the main component registered from JavaScript.
         * This is used to schedule rendering of the component.
         */
        @Override
        protected String getMainComponentName() {
            return "myapp";
        }
    
        /**
         * Returns whether dev mode should be enabled.
         * This enables e.g. the dev menu.
         */
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }
    
       /**
       * A list of packages used by the app. If the app uses additional views
       * or modules besides the default ones, add more packages here.
       */
        @Override
        protected List<ReactPackage> getPackages() {
            
          return Arrays.<ReactPackage>asList(
            new RCTCameraPackage(), // ADD
            new MainReactPackage()
          );
        }
    }

**Comment by ardowz** [comment]
Nice. I managed to make mine to compile, but whenever I try to run it on my phone. I get an error which is in (https://github.com/lwansbrough/react-native-camera/issues/165) was wondering if you guys made it to work in android completely.

**Comment by dangnelson** [comment]
Nope. Running into the same issue.

**Comment by Mo-k-tec** [comment]
Also doesn't work here.

npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save
rnpm link react-native-camera

And then add the changes @ardowz said + @dangnelson

**Comment by lwansbrough** [comment]
Hi all, please try with the latest commits from master.

**Comment by awitherow** [comment]
any update on this? i'm going through the steps from @ardowz now. I've changed the config & I've reinstalled the latest via npm but I still get this output.

```bash
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-camera : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by mkraft** [comment]
@rpopovici Worked for me, thanks.

**Comment by derdav3** [comment]
I solved it like this..
instead of importing:  
`import com.lwansbrough.RCTCamera.*;`
do this:  
 `import com.lwansbrough.RCTCamera.RCTCameraPackage;`
