### ISSUE TITLE
npm Error

### ISSUE THREAD

**Issue by wisdomdeng** [lwansbrough/react-native-camera#195]
I try to install it on an android emulator but I keep getting the following error messages when I typed 
npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/ruizhi/.nvm/versions/node/v5.5.0/bin/node" "/Users/ruizhi/.nvm/versions/node/v5.5.0/bin/npm" "install" "react-native-modal" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.2
npm ERR! code ENOSELF

npm ERR! Refusing to install react-native-modal as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ruizhi/Desktop/react-native-modal/npm-debug.log

Does anyone know where I got stuck?

**Comment by rt2zz** [comment]
react-native-modal is not a dependecy of react-native-camera, so your issue probably lies elsewhere. when in doubt `rm -rf node_modules && npm install` :+1:
