### ISSUE TITLE
iOS - Build fail: too many arguments on block call

### ISSUE THREAD

**Issue by andreacab** [lwansbrough/react-native-camera#202]
react-native: 0.14.2
After carefully following the steps mentioned in the readme, I get an error trying to build my project: 
"Too many arguments to block call, expected 1, have 3"

In RCTCameraManager.m there are 8 calls to a reject method with three arguments passed in. Xcode expects only one, any idea?

Thanks for your help.

**Comment by rt2zz** [comment]
@andreacab we do not support old versions of react-native, especially right now when this project is a bit in flux. I would recommend upgrading to react-native 0.20 and installing camera from master `npm i lwansbrough/react-native-camera`

**Comment by andreacab** [comment]
Thanks so much for your quick answer. Knew that would happen some day. Will update then.

**Comment by chenbin92** [comment]
@andreacab @rt2zz  I have the same problem, thank you very much

**Comment by rt2zz** [comment]
after reading more it appears the signature of promise reject was changed in 0.19. Your best bet is to either upgrade to rn .19+ or to downgrade react-native camera.
