### ISSUE TITLE
Prompting and forced acceptance of microphone permissions even if captureAudio set to false

### ISSUE THREAD

**Issue by abr54** [lwansbrough/react-native-camera#205]
This is related to the change that was made in https://github.com/lwansbrough/react-native-camera/pull/129 - as suggested there I have a use case where I don't need microphone access at all (a barcode scanner).

I've set the ```captureAudio``` prop to false but I'm still being asked to allow microphone access when trying to access the camera. Additionally ```checkDeviceAuthorizationStatus``` returns false in the case where camera permission is given but microphone isn't.

Ideally it'd be possible to just ask and check for camera permission without any reference to the microphone permission.

**Comment by RGBz** [comment]
I second this, the API should be updated inline with @lwansbrough's concerns from #129

**Comment by rt2zz** [comment]
we can either
a) add an optional options parameter to `checkDeviceAuthorizationStatus`. Something like:`{types: ['audio', 'video']}`
b) split this out into two methods: `requestVideoAccess` `requestAudioAccess`.

Thoughts?

**Comment by rt2zz** [comment]
after writing this I think b) is the way to go. It is cleaner and more explicit.

**Comment by abr54** [comment]
I think b) sounds reasonable yep.

**Comment by trabianmatt** [comment]
This looks like it was covered in 06ad9347a4399745bef0e1d012824e20e5e5a2b2.

**Comment by trabianmatt** [comment]
(and 990a1084d5ff5757d3f6267f7ce8d45f7b93b9df)

**Comment by rt2zz** [comment]
:+1:

**Comment by varunsdcet** [comment]
i am added permission of NSMIcrophone My app is reject . Please help
