### ISSUE TITLE
Very bad quality picture taken on android

### ISSUE THREAD

**Issue by KalebPortillo** [lwansbrough/react-native-camera#226]
### Environment
- **React Native version**: 0.21
- **React Native platform + platform version**: Android 5.1

### react-native-camera
**Version**:  "master"

My code:
```
render() {
        return (
            <View style={styles.container}>
                <Camera ref={(cam) => {this.camera = cam;}}
                        captureTarget={Camera.constants.CaptureTarget.disk}
                        style={styles.preview}
                        orientation="auto"
                        aspect='fill'>

                </Camera>
                <View style={styles.hud}>
                    <View style={styles.hudHeader}>
                        <Image style={styles.hudHeader} source={this.state.photo}/>
                    </View>
                    <View style={styles.hudFooter}>
                        <Text style={styles.capture} onPress={this.takePicture.bind(this)}>[CAPTURE]</Text>
                    </View>
                </View>
            </View>
        )
    }
```
```
takePicture() {
        this.camera.capture()
            .then((data) => {
                this.setState({photo: {uri: data}});
            })
            .catch(err => console.error(err));
    }
```

So the problem is, when I run this in one of my android phones 4.4 kitkat, the image quality seens fine:
![img_2016-03-16 13 18 27](https://cloud.githubusercontent.com/assets/10066821/13819824/a8481d1e-eb79-11e5-9fce-596caf4c853e.jpg)

but when I run this in my Android phone 5.1 the image look like this:
![img_2016-03-16 13 18 16](https://cloud.githubusercontent.com/assets/10066821/13819841/bb9a6584-eb79-11e5-8459-d657e05a8e53.jpg)

Im running the exactly same code in both phones..
I dont know if i should retrieve the image and do something with it before show in the image tag.
Thanks in advance

**Comment by agrass** [comment]
I have the same issue in android

**Comment by agrass** [comment]
I think it should be solved with this PR #211

**Comment by KalebPortillo** [comment]
Thanks for help @agrass ,
Any idea when this PR will be accepted?

**Comment by agrass** [comment]
The PR is in standby because they want to make the resolution more configurable. There are a solution proposed, but I have no knowledge of the progress of that, hopefully soon
