### ISSUE TITLE
Notes about base64 image & the CameraRoll

### ISSUE THREAD

**Issue by rt2zz** [lwansbrough/react-native-camera#23]
To display the base64 image that is returned by this module:
```js
//style height & width and source.isStatic are all required
<Image
  source={{
      isStatic: true,
      uri: 'data:image/jpeg;base64,'+base64image,
    }}
  style={{height: 100, width:100}}
/>
```

Also images can be saved to the CameraRoll with the following patch: https://github.com/facebook/react-native/pull/1111

**Comment by jtremback** [comment]
Is putting the data over the bridge and a base64 conversion twice (once from the camera, once to the screen) a concern at all?

**Comment by lwansbrough** [comment]
@jtremback Yeah it's slow and locks up other actions from taking place over the bridge while it is being sent as far as I know.

**Comment by jtremback** [comment]
I found it quite slow as well. Is the base64 conversion option in this module ever a realistic option?

**Comment by lwansbrough** [comment]
Potentially. It has mostly just been kept as the default for backwards compatibility and predictability.

**Comment by jtremback** [comment]
Kind of feels like there needs to be some code around handling files and data "over the bridge" in React Native in general.

**Comment by lwansbrough** [comment]
The bridge is not really designed to be that. React Native is designed to reduce the workload of building a native app, it's not really a "Javascript all the things!" solution. The current suggested method of using file URIs works just fine.

**Comment by jtremback** [comment]
Off topic for this thread I guess, but I was more thinking about an
abstraction that would let you manipulate data that is on the objC side in
JS without actually copying the actual data over.

I guess saving it on disk and reading it when I need to is good enough for
now though.

**Comment by lwansbrough** [comment]
I don't know how you think that would work - the only way to get data between JS and Objective-C is over the JS bridge.

**Comment by ahh2131** [comment]
Sorry if this is a silly question, but how do I get the base64 data from the camera without saving the image to the camera roll?
