### ISSUE TITLE
Can only get aspect fit to work

### ISSUE THREAD

**Issue by jonsherrard** [lwansbrough/react-native-camera#24]
Hi! First of all thank you for such a fantastic addition to the react-native eco system. It opens up so many interesting applications!

 - Regardless of the value I use with `aspect={Camera.constants.Aspect.fill/stretch/fit}` the aspect always seems to be fit
 - I've tried setting heights on the `<Camera />` element itself and also wrapping it in a `<View>` and setting height and width constraints on that.

 - Regardless I only ever get the vertical image with black lines at the side. (I have 60px of navbar at the top)

 - I've tried all the constants as strings as well, and also as capitalised strings which throws a deprecation invariant warning

Any pointers would be very welcome. I'm using react-native-cli@1.3.0, and react-native@4.3.1, with camera@0.2.1

Thanks again for all your work on the react-native-camera element.

Jon

**Comment by lwansbrough** [comment]
Looking into this now, thanks for reporting.

**Comment by lwansbrough** [comment]
I can reproduce this - looks like I didn't catch the bug because the demo uses the screen's aspect ratio which matches the "fit" aspect. Hah.

**Comment by lwansbrough** [comment]
Ah, oh boy. Don't think this fixed it correctly. Now everything is `fill`. 😁

**Comment by jonsherrard** [comment]
Thanks Loch, I owe you a drink if you're even in London (UK)

**Comment by lwansbrough** [comment]
Cheers. 🍻
