### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by verystrongjoe** [lwansbrough/react-native-camera#247]
I got the following error whenever I build with this libraries.

(null): error: make directory /Users/jouk/Library/Developer/Xcode/DerivedData/mobileOpenAlm-cmeqcfhepzpgbweuaddwjfottcaw/Build/Products/Debug-iphonesimulator/mobileOpenAlm.app/ios: File exists

So, I closed my simulator and xcode and run again and I got the other one.

(null): error: open /Users/jouk/Library/Developer/Xcode/DerivedData/mobileOpenAlm-cmeqcfhepzpgbweuaddwjfottcaw/Build/Products/Debug-iphonesimulator/mobileOpenAlm.app/ios/CameraFocusSquare.h: No such file or directory

I tried to work around this with both automatic and manual installations.  But it didn't work yet.

**Comment by rt2zz** [comment]
What version of the camera do you have installed? I am not sure when focus square was added, but i have successfully built the latest on master with rn.14

**Comment by verystrongjoe** [comment]
Sorry! It was my mistake. I set the build target as a camera project itself. I changed that to my own project. it worked.
