### ISSUE TITLE
playsoundoncap error on android emulator when camera capture ran

### ISSUE THREAD

**Issue by Intelurate** [lwansbrough/react-native-camera#255]
### Steps to reproduce
1. Just did a recent pull and started getting this error in the android avd emulator when I ran camera.capture. 
I have not tested this on an actual device. 

<img width="430" alt="screen shot 2016-04-10 at 9 31 29 pm" src="https://cloud.githubusercontent.com/assets/3150171/14414621/c5b7fdbc-ff63-11e5-85aa-a9e6bc285755.png">

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
ALL LATEST VERSIONS 

### react-native-camera
**Version**: npm version or "master"

**Comment by rt2zz** [comment]
Can you reinstall from master, I pushed a [fix for this](https://github.com/lwansbrough/react-native-camera/blob/master/Camera.js#L164) issue a few minutes ago.

**Comment by Intelurate** [comment]
Thanks that fixed it.

**Comment by rt2zz** [comment]
👍
