### ISSUE TITLE
Displaying the captured image.

### ISSUE THREAD

**Issue by antoinegrant** [lwansbrough/react-native-camera#26]
So I'm to clear as to how we go about displaying the captured image from memory or from disk? Could give an example?

**Comment by rt2zz** [comment]
To display the base64 image (i.e. target: Camera.constants.CaptureTarget.memory) the code is roughly
```js
<Image
  source={{
      isStatic: true,
      uri: 'data:image/jpeg;base64,'+base64image,
    }}
  style={{height: 100, width:100}}
/>
```
where base64image is the string returned by the capture method.

To display the `target: disk` image, the code is roughly
```js
<Image
  source={{uri: imageURI, isStatic:true}}
  style={{width: 100, height: 100}}
        />
```
where imageURI is the string returned by the capture method.

You will probably need to play with the width/height, and resizeMode prop to get everything the way you want it.

**Comment by antoinegrant** [comment]
That very helpful, thanks.

**Comment by Mayzie** [comment]
Hi there,

This does not seem to work any longer on React Native 0.44 for Android. How can I achieve this (displaying a temp, or disk, image)?

**Comment by npomfret** [comment]
@Mayzie - what doesn't work?  do you have an error or a stack trace from logcat?

**Comment by julienvincent** [comment]
Can confirm this no longer works. No problems on a simulator, but does not work on a real device

**Comment by julienvincent** [comment]
No nevermind, after reinstalling it works as expected

**Comment by pablodance** [comment]
brilliant - thanks very much @rt2zz  - saved me some head scratching..
