### ISSUE TITLE
Get Base64 image

### ISSUE THREAD

**Issue by timotius02** [lwansbrough/react-native-camera#278]
How do we actually get the base64 image that we took?

I've tried playing around with the captureTarget, but it seems that those only return the path to the image. Is there any easy way to just get the base64 image itself?

Thanks in advance

**Comment by stoffern** [comment]
You could use "react-native-fs" to read the file into base64 until the Base64 will work 100%.

**Comment by andrerfneves** [comment]
@timotius02, make sure you have memory as your captureTarget

`captureTarget: Camera.constants.CaptureTarget.memory`

Then take the picture:
```_takePicture() {
    this.refs.camera.capture()
      .then(data => {
        console.log(data);
        Actions.preview(data);
      })
      .catch(err => console.error(err));
  }```

And then to view it do something like this:
`<Image
          source={{
            isStatic: true,
            uri: `data:image/jpeg;base64,${this.props.data}`,
          }}
          style={styles.image}
        />`

**Comment by charpeni** [comment]
`Camera.constants.CaptureTarget.memory` is deprecated.

The best solution would be to read the image as base64 with `react-native-fs` from the path returned by the `captureSuccess` callback. After that, you can display the image with : 
```js
const base64image = await RNFS.readFile(photoPath, 'base64');
```
 ```jsx
<Image source={{ uri: `data:image/jpeg;base64,${base64image}` }} />
```

**Comment by stoffern** [comment]
That is actually not correct, it would be like this:
```js
import RNFS from 'react-native-fs'

RNFS.readFile(file.substring(7), "base64")  //substring(7) -> to remove the file://
.then(res => this.setState({base64: res}))  //res will contain base64 with data:/image/*:base64;..

<Image source={{ uri: this.state.base64 }} />
```

**Comment by mtwallet** [comment]
@stoffern I wonder if you can help me? I am trying to implement your suggestion above for iOS but I am getting the following error:

`2016-06-25 15:32:28.350 VehicleCheck[2438:1856471] -[<CALayer: 0x12df60ba0> display]: Ignoring bogus layer size (288.000000, 238119.000000), contentsScale 2.000000, backing store size (576.000000, 476238.000000)
2016-06-25 15:34:06.245 [info]`

I have `captureTarget` set to cameraRoll (although it doesn't seem to matter which setting I apply) `captureQuality` is low and my code looks like this:

`captureImage() {
  if( this.camera ) {
    this.camera.capture()
      .then( ( data ) => {
        RNFS.readFile( data.path, 'base64' )
          .then( res => this.setState( { uri: res } ) )
      });
  }
}`

If I log the output of `data.path` I get:

`/var/mobile/Containers/Data/Application/8071BF6D-4705-4A02-8746-4C7AC5BFE99E/Documents/6BB91BF9-BEEA-44C3-B823-38506D4FFCBB.jpg`

Am I doing this correctly?

**Comment by stoffern** [comment]
@mtwallet To me it looks like a informational dump, not a error `[info]`, anyways this is related to native-camera capture size and scaling and does not give us anything.

I have not tested it on iPhone, but what output do you get if you run this command:

```js
var file = '/var/mobile/Containers/Data/Application/8071BF6D-4705-4A02-8746-4C7AC5BFE99E/Documents/6BB91BF9-BEEA-44C3-B823-38506D4FFCBB.jpg'
RNFS.readFile(file, 'base64')
.then(res => { 
  console.log('read ok')
  console.log(res)
})
.catch(err => {
  console.log('read error')
  console.log(err)
})
```

**Comment by mtwallet** [comment]
@stoffern Just tried and I get:

`/9j/4AAQSkZJRgABAQAASABIAAD/4QVuRXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAABIAAAAAQAAAEgAAAABAByCmgAFAAAAAQAAAaSCnQAFAAAAAQAAAayIIgADAAAAAQACAACIJwADAAAAAQGQAACQAAAHAAAABDAyMjGRAQAHAAAABAECAwCSAQAKAAAAAQAAAbSSAgAFAAAAAQAAAbySAwAKAAAAAQAAAcSSBAAKAAAAAQAAAcySBwADAAAAAQAFAACSCQADAAAAAQAQAACSCgAFAAAAAQAAAdSSFAADAAAABAAAAdySfAAHAAADOgAAAeSgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAAAJCgAwAEAAAAAQAAAMCiFwADAAAAAQACAACjAQAHAAAAAQEAAACkAgADAAAAAQAAAACkAwADAAAAAQAAAACkBQADAAAAAQArAACkBgADAAAAAQAAAACkMgAFAAAABAAABR6kMwACAAAABgAABT6kNAACAAAAIgAABUQAAAAAAAAAAQAAADIAAAALAAAABQAAHMEAAAUYAAAe1AAADY0AAAPzAAADawAAAAAAAAABAAAAUwAAABQAXwBHAIwAP0FwcGxlIGlPUwAAAU1NAAoAAQAJAAAAAQAAAAQAAgAHAAACLgAAAIwAAwAHAAAAaAAAAroABAAJAAAAAQAAAAEABQAJAAAAAQAAAJ0ABgAJAAAAAQAAAJUABwAJAAAAAQAAAAEACAAKAAAAAwAAAyIADgAJAAAAAQAAAAAAFAAJAAAAAQAAAAEAAAAAYnBsaXN0MDBPEQIAWgBUAE8ATQBJAEgARgBaAJoAyACqAKQApgB4ACMAEABfAFcAUwBOAEwASABGAJIA1QCdANEA5QB2AGsAEAAPAGUAXABWAFEATgBKAEcAqwCXAOsA2wCzAH0AaAAIAA0AagBhAFwAVQBSAEwASQDFAP8A4QCsAHcAngCTAAgADAByAGgAYgBaAFUAUABPADEB/wCmAKsAuQBxAEwABwAMAHsAcQBpAGEAWwBVAEwALQG/AOcArwCKAIQAQAAHAAwAhQB6AHEAaQBiAFsATgA+AfYAzACaAFMATgBbAAcADACQAIMAegByAGwAZgB4APwArgB0AFYAYgBNADMADQAMAJsAjwCEAH0AeAB2ANYA8wBlAGkAMQAUABQAHQApABMApwCZAI8AiACGAIgAAAGZAWoAFAAUABsAJQAvAE0AkgCzAKUAmwCUAJQAnQBBAd0BDgE3ACEANwBLAIEAzgD0AL8AsAClAJ8AoQCuAI0B8gGaAakATwCdAMQA3gDbAM4AzAC8ALAAqQCtALsA2AEVAsgBBgGLAK0AuACqAJMAhwDXAMgAuQCzALYAxAAEAjYC2AFeAc8AYwBaAFkAUgBVAOMA0gDEALsAvQDKAEICVwLnAZ4B+wCmACwAMgA4AEEA7QDcAMwAwgDBAM0AyAF1AukBvwE9AdIAcwAjACsANQAACAAAAAAAAAIBAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIMYnBsaXN0MDDUAQIDBAUGBwhVZmxhZ3NVdmFsdWVZdGltZXNjYWxlVWVwb2NoEAETAAEu1rzEVnwSO5rKABAACBEXHSctLzg9AAAAAAAAAQEAAAAAAAAACQAAAAAAAAAAAAAAAAAAAD////lKAADLO///9f0AAA0g///1VwAAEMwAAABTAAAAFAAAAFMAAAAUAAAACwAAAAUAAAALAAAABUFwcGxlAGlQaG9uZSA2IGJhY2sgY2FtZXJhIDQuMTVtbSBmLzIuMgD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgAwACQAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAAgICAgICAwICAwUDAwMFBgUFBQUGCAYGBgYGCAoICAgICAgKCgoKCgoKCgwMDAwMDA4ODg4ODw8PDw8PDw8PD//bAEMBAgICBAQEBwQEBxALCQsQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEP/dAAQACf/aAAwDAQACEQMRAD8A96ll5xms+SQZ5pryetUZX5zmvk2j34iyyVnTSgDmiSU/Ss6aT3qLmiRHLIc4zWbLMSMA81NK27JrKlkHQVLZsitNK2eDWVPK33SeKuSk5ye9Y07sOlLmLK0zjpWLOwDE5NXp5DyO9Ys8uaaYNFWZmxkHNY8zbDnrmrs0oGTjArHkmBySeDWkUQ0VJpuSazJGDfODk1cmYMSM1lTYHyjkEVokIilmLkGQY28cVnSOueBxSu5yRjNVnLA4xnNaJEyGyFSB61AZCG9hTXYk9DURf+GmUf/Q9YkkwOTVF5c59ulRSyZGM1SaQdPSvlGfQRQryHpmqMrjOOtPdyOepPaqUj54HWsmzeKIZHGDzWdM+OoqeZjms6V+MZqLmqRTml4rKuJMjNXJW4JzWRPLnNCLsUbhz161kTyHIK8AdauzSHnjJxWLNIOQOPxqkS0VJpPmOazJXHQ9KmmducnismZyeP51skSyK4kIJxzWY8p6nPFOnYjOOcVQlk5yeeOlbRRmxHkUr0qizncSOc0O5wAPqaqGRuxqoxIHO5zk9qhLgHNDOecmoGJ3ZBqyuY//0e3dzVZmwaczEioyTivkZyPpVEiYDOaqOBg4q0wY4Oahdc8VhKRtGJmSe9Z0xHIrUmU5/wAKzpo85JqFI1ijGuMD5qxZznrW3OG/KsK5B57VUZFtGRM3BNYdw/zEkYrVuevBxmsG4Yg5PNaxMWjPmkHXpWVKx5qzct3Ix71kzPheT+VbxM2QSOvIB61RlXP8WBTpWDcVSY/WtjNsa+T3zVZwduO4pTk8VCVI5JrVIjmAuG+9UJfJJzkU1ic8dqTbkdQKTRSZ/9LstvGKbsOatCM9ak8rua+JnM+sjEobMc1BItanlcYPWoTF1rByNoxMWSPtWbNG2D6V0EkfWs2eI9O9ZuZsoHLXCVzl1x9RXX3cWAc1yt6u0VcJCcTlrpsHBrnLl/m9q37w4ya5O8ccnNdlN3OeRnztnv8AnWTMwJwD0qS5esuV29eldcEc0mNkkGDjgCqpm60x2BFVmIwTmt0jJsdJJu6nFV2lJ6mmk9hUbHNaCJPu96QOVOeOKjLYqLJxihoVz//T7d7+KEKZIZBn/YNOGraccBnKH/aUiusgdnZIkUSMeAMZJNfXPwp/Z/i1QQ+I/G1oqxcPFasvLehf0HtX5Xl+MrYifIo3P1HM8FhsPD2kpWPl7S/h94w1zTU1jSdGuru0k+7LHESpx6VmX3g/xLYk/bNKuocf3oXH9K/YO3t7Swt47e2jWCGIBURQAoA4AAFUtQvkhQxxQi7usAiAMocg9/mOAK+ullSt8R8Ys2d/h0PxjnsbiM4kjZD6EEVlT25zyK/au50HQbyP/TtPt5Cw5EkSN/SvN7/wH8MdXZi3h+xmhUkPIIwnPTA24ya8+plklszso5qn0Z+QF1b5BxXH6jAQDkV+sPif4JfCEWzXX9kNGG4/cSuoXPc8nArxPVP2cPBOpXi21hcXMCSoX3pIsoTGMA5GTmphgKvRHR9epdWfmZqGVJPSuIvpASa/SLxD+x7ZMGOm+JGWRj8qSQg/qCOlfIvx1+Cr/BjRDr2s+I7O4Vm2pAqsszepAORgDk81208JUW6OOpioN6M+dJpOvtWVLIc81ykPjzQ71Q0U2QfUVow6rDfkC1DSE9lQn+QrsjRkt0YOtF9S8zgj0qqW7dq1V0PxBLGJE0q6Kn+IQSY/PbWbcWt7AcXFvJEw67kZf5irSM1UXcrlscEVGW9DTGkHfrQGHNaBckyMY70m7ioy46igDPIqGhn/1P1b+EnwC0zwiIdb8Sqt5quAyoeY4T7Du3vX0bc30VtEWyCR2HPSufutVmhjYopWRuc9cA9M1xOp60lwyaPHqKW+oXW4qCpLDaPm2kcZHXrXyWFVOjHkpqx9BiFVxE/aVmdfqGr3cSAWdtJczXA+UoBiMY6uCQB9M81E9zY6PF9tvP3tzj5pSMuWb+EdSBnsDgVztnNcaTpqw314bqUKACuE3EDGAPfqcmuZlvXv5JMTKxJw4GD5fqoI7+9ae1bYvqyR1M+uX1/K0RVo45FG5g33Qf4QO59TWRc6xaaTbSSTMkMMQJOM8AcnisfUNTg0i1e5uZvLhhAHoPZR6k9KwLKK48QXP9tyqZNOuYgRDPGA4PGMZJGOua1jLqwcbaIvza7qt1a/arJLe6ikAwscpDEnp8pB6ikllXSbeNryYblxnGASx/hAAFP1N9M0WOTWHhSH7PH95FCttUfdGP0r5w1/xuNUuF8QXIuLOSKNhHFM4Kxp3cheNxHr0p1cZGmuZhSwkqjsjt/iF8UNK8M2FzqVxMY3jXLDg49FAweT+tfPPh7wH4Q8fzHxp8XZIdUl1AAwWM8aslpCxO1fncAE9WOK+Ff2n/il4h1jTHuvDcpj02zmG+bk7ucbyfTPSue8E/Cvxn4t0+21HUvG06QXKBgsMDuSDxw0joDXZgcPjaz9pThdG0qmVwg44mrb0v8Aofq1q/hH4GeDPDWpa34M8L6TqM+k2M9ybZILcMzwqW25AOM4614t4B/bd/Zwm0K2v/EEelaLNLbB2ggT99FNjlCNuOKxvhd8OPDXwwsb1bjVbvV9Q1ZRaFrgoEjEmAQUVm4ORzmvnL4d/B34IX/xv8TfC/xl4Ogi1DTxHcW7PIypMkwLEhV7ZIr67A0q8bU61NczR+d5m8JKrKWHm3Bbd/6ufQs/7enwq1TxRYaLpFwt1bXVzHCEhtGLkSMF5Yemc9K8s+Mvxx+Inwm+KviLRdU0CbxDoGppFNp4htUZY0IG5C2wnIYcnOSDX0EPhj8LfAskFz4O8P6RY3EGHjlKKSkgBKnLv2YYNeHfHTxT4y8QfCa+8b+HbhY9f8H3iNfiEK3nWobOVxkAbTnI9DV5hh6lNqbil0OfB1YN8sWz5o8T/Grxl43Zv7D+EaQGVZE3vahcCU5zlgMbT909qt33ww8SeJPhrpl/p9ja6N4qtmb7RblwyyxZIG/GcHGDXsVv8UPhDrXhzT9Zubq8uLm9iR5I5ZC0cW5VDgDcobDBsemfauK1D4vfCjTdUtV0C1+w75VhnlaYHzoHGxt6ZOCDtYYPXPrXlY3CtrmVtD2KGJltqfLb+FvHVtMyX2qaVCEPzBC8uMf7ortdL0LSraJh4k1SRXUqC8Nq6xpu5G4uc8jpU1x4muv2cvH2r6VeQQ3+iaxBKbUXSeZFLbz8lD7o3IxUXin9rfW/EiX9paQRQ2+owLbzRW1ruDJHxH8zAnci/KDnOK4fq/Mk0d8cVNPc/9X9W/EfibWGaLR9C87zb5gj3Uce9IgMbs5P15xjNbkjWdg0dzcNvljQRxDHALdTj1buayNN0vSfDysmjwrbiQDdsZiWx0zuJ5qh5raleyxLlrfbh5W6D/ZQfzIr41WPreUvTtPqrDbMIZAf3gUE4X0Q8c1Nd6hY6RaG4llFtDAMvkckf/XolmsLC0CYEcUWAD169Bise5vdLnklstRVhE0RkZnTCbQemRn8qpSJZWtMavePqDRQXGmyANE24SFXHOcetbt9rEOnWpmuLgMF5AY8YHuOlcpe+JNE0axK6SvkqQW+RQitv9uOfWvnfxb41n1WQ2wbEanDEfy/HvXLicfGB0YbAymdR4w8fPrIa2hfMEZOB1ViOn4V+cn7TPxzGjaZceGNDnJvZfllkU9M/wAP+NelfGX4pweAdGdYJA+oXS4jUdUU9/8ACvyc8eeJLvW7mS7uXLSSsWYk0ZPhZ4mftanwr8S8yrRoQ9nT+Jn1pfwTeJPgzqEkEnmi8sNw9dwAJH5ivHvAv7SviTRfDtn4dsNNuLu4tEEYMUYZuO2drHryPQ16t+z7qCa/4Fl0SZ93ls8QB7BuR/OvWP2V/ETeG7nxX4FmaNZ9H1B2Rgihmjk5HOMn86/YstlOVRRpytdH41XlCEZKpG9n+Z5hoXxc/aW8STInh7wHqd8JCoVpLeXbxwDuKqOPWvcP2pfA3xNg8deEPij4PEGk+ILywisr9LiVY1WZgPlLN8pwxIr66vPFwlt7Qm6UYUtIwIXDE9Dz2Aryn4y2th8TPhH4r0qwnS91TSEj1G0ZHDPG8ZDdj6r+tdeZYarCKqSldo4sLioOolGFk9D54sv2cP2t/FE5XVvGOmacXXcyxStOyj6RoR+tfQvwJ+BN98NJ/ENp4/8AGZ8SnxFbixktfs7RwrkkEsZDnPOBx3rB+HP7Tfw+tPCWka9rGtRW1/LZrFdQMx8xZAMMcYIzkZGRWN4p/a5+E11fy3VveSSSPj/Vpksw/iJ45J54Fc+Kw1OUXzTv8zrhVrPRQt8jw7Sv2Z/hAvxE8Q/D7XbjWYrvRissdv56xxSQy/MDGdpJAzivoex/Y2+CNhoq69p2hnU3giFw4ubmWQAA4IyCoLL1YY6VzXxrutS1ey8DftNeCNPnumeH7Lf26oRLJASQCV6nBB/A1yth8b/jlqdi9j4U+H+om0ucgl0KoQ3XkgcHvzXl4apScLS3O+ftpPmi9DsPi/4ffX/AGpy6BY276tpMXm2qSxLKBGmMqgbODgYFfG3gHxJ4Z1d477xVFcSWcsZRks2SB45hgc5GMD0r638FH473niWzn8WaHZaNo5JFx5s6mTyyOQFBJJr5g+NHwXtPBfiibVdP8VR6Fo3iCcvDCYmc+a3LBNvGK8yfLCbUdmejh56Wluf/1v1ju7mCe1ZcDceCTkH8KqB7S0tWQYijQFiScAAdajkkkkLCQA46Zzg/j2ridV1C31NJrJSwktZF8wCT5WQ/ezgg9O1fD83c+z5Og7U9XvbttO1K3jMuniXLGNgwweASoGcD68dazfEfiFMFEYCPH3SM7sdAfpXO6t4igtbc2OnqIY0GAVAXH1ryDWdbkbc5Ys5/WvMxeYqKtE9DDZe3rI0vE3iJ5nYK+ZW5AXkAV4h408X2fg/Q5NUvSN6g+UmeXf3rWvry10u2u9Zv5diKC8jE9cDhRX59fFTx3q/jHVmnKMlnESsSdgv+NceX4SeKq2fwrc7cbiI4endb9Dyr4j+L7zxRrVxqd+7O7kkAnge2K+fNTlMrtzxXca1O5mdeea4K9BPpX6NQjGEVCK0R8TVbk3KW7Pob9mvxBJZard6WXwsm1wPccV2HjPwt4nm+MZt/CesJosviGEM0krsikxjn7gJJ9sV88/CPU30zxta7W2+cdh/Gvqn4w3w01fCPjKJQsmnXwSV/+mcgwRmvocJP4bs+Kx1Nxryst0dto/7Kfi/Xpdus/EOadtpkZLWCVztAyeZHUfpX058EvhZ4F+E736Q6lf6xe64i2byXRVY1Rj02KT1bHJNcB4U+PPg3wrbeddX9vI0hQncx3BByVG0965jWP2k/hss8zQXrHc5aNY0OEOcrgk9q+kq4bDxi3za+bPClUxE9LaeSKvhj4cfCfTfi54n8B+LvB0Et9aBLu1aWR9kkUvJIRSB1r6u03wL4B03R4p/CvhzSoL5ldxEtrEWAj+8AXDEnAz1r5W/aD1m80zxH4F/aH8PW8l1BqFkkFyiKctG65GQB65FcjB+078TNRgNj4P8ACd6VkyGAVyDu49BjI615WGrYeMLTWqPRlSr1GpRejPu7RtdufHdjqHgPWJvIF/aslm8arGYHRcDYAABgcj6V8t/CLx74iWxvvAviy4kuNU8KXjW0yyud0kaN8p5PQiuf8A3/AO0/4j8YaLcxeFhpdslzEzTXC+WiIGG4knnG3Ndh+1H8JtR0Xx9F8SPCfiC30FPEKR2908nETTA7QQw4ya4Z4mnCo5wWjNaWHf8ADm9T37x1qPhfU9OOpaXcxRSK6+VEpUOyOMuHUKu3YeBycivn34g+E7D4u/DrUfBSyRnV7P8A0iwckFlde3rjsfY159a/s4+LNXnjtta+I7TzTkBY7KKSUsT2GOK9L8C/CDwz8H/Eh12+1DVNV1JImRFuR5SfPwW255FLEylUWkTeEIw1UtT/1/0S1nXrh7jyNPfyEtzklxlZfbrnFcFrPiKZQ7bh5kgHmMg25I45/wDr1g6rrG64maFwIHHCbeh7kGuJ1DUJNuCwxjkmvyfGZhf3Yn6hhsFbVk99qysH3tv9TXJtIcSXFzhI+vJ4VBUbg3DLMv3c5AHf3r5y+MfxJjtP+KO0SXNxcYEzA4IHdRXmYajPEVFThuzvrVY0YOcjK8eeKZfG2rtpelSGPS7Xjav/AC0YHkmuC1jwiI9PllEWCFPbjiu68A+Hy0KSspAwNwxkn616d4g0JH0eRoBvOMcDLfzr9dwGWww9FQifnGNxsq1XmZ+W/iXTJBeShBjJNeaX8LRko45FfRfjGw8jWZkxkBj2P6g14n4itfJuPrUbalLU5PRbs6Zrtner/wAspFb8ARX3H4wsF8UfDq9t2RnSNBOuOcY5BFfB0i7Z0PvX6CfCnU7XU/AkazSDzGjMe0jkgDBFelQd00fOZvHlnGaML4TfBL4P+KvDNh4g1u71O9kuB80aypDGD3HRmr6dX4F/BnwStjdReE4LlrpS6NcTvcYKno2CFz7V8ffCXxLp/h+w1bwxq92tr/Zt5Kqbzj5ScjFe6zfHjwTZ+H4tDu70Sm3mMyyLkkbgAy/Q4Br6ehHDqClJI8DEe3c2rux9L+MWvfiB8Otd0nSo4NP1DSbfzrMIuEVUQ4AX6riuI+DvxSvvFXgXSNTnlKmMCG5SDbCxaI4cZUDBNcf8I/jr4Y8V+PrLwvpiSynUopbZiV42lS2TjoAR1NfPd9r/AIn+BvjXxL4VstJlvrG6u2ubYKrFVEnJAwPWuCFejSrSfRl08NUlDk6o/RjxOt5HplhqYhmgmnLuyBpJEWBseWzFicMee/SsO/8ADtt8VPhN4u+HV2ol1COBrzTmblklT5ht9MMPyNfE3/C4v2ivFsSWmlaHcmHACqwZgFHQYJP8q+gP2ctB+OzfEmy1/wAfzRaRottHK06zYXzVZceWMgckkH8KxxeKp1I8sdzT6nOmueXQ4r4M+NbrVfDFtJcztbanpTG1uMNtkVo/lPPrjivefGfjTwPc+H7O1l1SKW8syI4WKCEpb4yVk+Yhm3c5FfN/x7+Clh4e+LEy6X4gbQLLxXcedEo/1bOwy2COn5Vix/s0eDoWD6/4su7w9xErfzO2ueGMlJaRvY7XQgtebc//0Pe7u/IJVTgVzF05vnCk5iXng/ex/Snz3lxcTi2VNyg/O3TA9K5fxn4qsvBmiXOs3jA+Uh8tOOT/AIV+Dx5pSSW7P2dpJXZwXxf+J9p8PfD7IjD+0rgERqP4Qe9fB2halea1rTalqR82aZ92WyeprlvHfjnU/HviGTUr6QmPcdi9gM11fgyEGWMryV9elfpmQ5WsPC7+J7nxOb411XZbH3F8PpEjtYgjeWFGTwcfpXq+piCbTjGfmKjPGcH3Ga8y+H8G6BV3YIwQvHX26flXq8vntbsTEWAXBBGc+4HWvrY7HzTWp+dXxTsxBrsrxDbljx3r578VQbo0kI/Gvrn41aXCt888SsueSG9fbNfKeuqXtdrfw15c3qz0acdDx66QhsjtzX1f8Cb0yWMlqefLkOB7MM18wXsXUCvb/gZqb295PbshdXCE46jacE11YeR5Wb07wudJqnw98N658VJtH1a+k077epmBjXdv28HAyBn8a+i/CH7NfwsuYpbn7NcagluVDy3U8dvEGboCTu5PYZryT4v+Rouv+EvFEChRFcGKVvVJOx/Kvpfwjrmj3Wk6p4Z1S4+y2+piKaG4ILJHLEcruA52kEg46V72Bw1OcXzas+cxOJqJJxejOm8M6Z4Z+FGryroPhi307UEQxl3ZpH2sM8EEDB45Arlvj5rGqeH7vwh8W9I2Jpl1PFFeoyq+DKMc5BHysCKueNvFGhyXOlpDqcVw2n2cdvNOTtEjx55APOAMDn0qlrL2fxS+CXiXwnpsyXNxpjfaI9pyV3ZZcfRwaWPoU4KMorY58NOfP7z30PomxurLUtF0eV724V9baSOOaOTbFDICNisgAyGyMnPQ8VNqmkWs93/YIt/KuHsftFrcB2LSywqTNHJk4zlWHGMECvg74cftN2PhPwnY6VrsaXMtrtLRTLuCTRcBxyCGGMH171bu/wBsa+Q3a6Ss0v2t5HOFDEGX7+w4JXd32kVpUxdNLRm0MFNvVH038VdPg+JX7PV8UhEviHwe8dxay/8ALQJG2cA9cFMqfpXkPgnxLF4t8KWWqq+ZQgSUHqHXg1D8Afin4l8W+JNR09tGMWjy2Uwu2kB6EYTAPU7uwr5+8R6H458CeItU0bwtNHHZzztKmSV2BznGCK8pYuNObfRnZSwrcXB7o//R9PuLmy0izlurxtkMClnYnsK/MH45/Fm88ca5PpunzMmn27FVUcBgK9b/AGk/jbJcyt4P8Ny7Y0OJnU8n8RXxLChkfcx5PevzXIMp5V7Woteh+lZrj+b3IP1NTT4csMV7J4OtpfPV4j8xPKnp+FeY6bFyB+eK9d8M5SSPYF7ZJOMfUV9lSkfMVFofZPgB5ooI2GWUgDZnnI9a+gLab92I5YwQwz82cg+x5r5q8CTS+XGwYsV6gdR7cnke1fSWlyx+Wg2FSF5UgYOOwHXHtXq0paWPNqLU+W/jnoweNrlUHzDjGcH35/wr4P1q3O2RcYr9QPizYLqGlSvbxfcHbpnH6V+b/iayMV1LGwIJJrzsTozuw2qPD7yHOa7P4SXxsPFkCfwyMUPvuGR+orFv7Ygk44o8I3g0zxPYu6jiZGGeM4PTNKhUMsfR5oNH2B8YdBOu+A2EWFmtXV1J7MuCM96+ZIpPHV0ixNqSwIBjCljx+lfdesWVlq+jyo11GVuIhkM67kJHAIJ7eteI2/gXQrMgajqqJg/wspP866q2Jkn7jPn8JStG047Hh0Hg7Ur0iTUNXmkz2UYH65r9H/2TvA+k6N4J1eYKWuNTkMckshyzRqMKvoACTXz/AGUXwp0fY2oah52OwOf5GvYNC/aN+GfgzT/sGnAtGvIAIArGliHzfvJaGOOpznBRpRZ4X40+FNlYeMNQgGlrI5lZtwjznJ+lWbD4Z61IB9h0dwPaPFej6z+2N4JW4a5i0uJ5f7znP+FcPf8A7ddxbrs0u1t4QM42xr/9euSVG7+JnTGdey9xfefUf7PHw017R9Xvr/VbU2kUkKopbGchs9Pwruvi98Dz4v1ODWtNmjt5CgWXIwGPY1+bupfttfEC+DR2dzJGD0CDaP0xXnmp/tOfEjVCTPqEwz6uf/r10cl4cnKzm+p1fa+05kj/0vyXubie+uGubly7scknnrVi2j6Ec0sdrJuwVrSt7SVfm2cV87zrY+t5XuaunphhgZr0vQGwVDAA5rhtPgYOMoTxmu+0YYYNsOAcirhMzlHQ+mPAVyCqQOcMOARx17ZP+FfTWixQNAuX2tnIK5GfbngV8oeDbmPzE3xsucdTwSPUdjX1FoUr3MKiNArH0Pp2PavSozVjz6sTT8VaWt1pro6FQARu5wf97BNfm58RdJ+xapNE67Pmbb7/AEr9RnSWS2ZZSURhwORgevviviP4z+HDHdSTAZLZ5xnP+Fc2NWlzXCb2Ph69tG3sCvBziuC8TRCzszcnh1I2EHB3e1ex6jZtC0hkYLGmS2TjGO9fOHifUv7V1R2ifdbx/LHjoR61hl6c5+SOnHyUYa7slPjrxEybZLln7ZOc8VRn8V6zN1nK59KxDDz60vle9e37GHY+f9p5lt9a1R/vXD8/7VVJLu6l+9IzfUk0oj46U5Yq0UY9hXbIAzk5PWu/8F32j22oC41K3WVolLRo2Npk/hznqAeoriFj9akWPn0qKkbqxvhq8qVRVIq7XfU+grfwfdaur3+6P98SxK+/sOlXofhnIw3tG8g9hgV5p4U8e6z4YlUxv50QIyp649Pevrrwj8S/B3im0W2d/sl3/Ej4AJ9jXz+YV69FXiro7cHQpVZN1JWZ/9k=`

**Comment by mtwallet** [comment]
I've adjusted my code to the following and I am now getting the base64 string as I expected:

`captureImage() {
    if( this.camera ) {
      this.camera.capture()
        .then( ( data ) => {
          let base64Img = data.path;

          RNFS.readFile( base64Img, 'base64' )
            .then( res => this.setState( { uri: res } ) )
        });
    }
  }`

@stoffern I really appreciate the help there!

**Comment by charpeni** [comment]
@mtwallet like I said. :)

**Comment by stoffern** [comment]
@mtwallet np ;)

**Comment by pacozaa** [comment]
This is weird why #892 point to the direction that using `data.data` is fine but this is even an older issue but suggest `react-native-fs` which i guess it's more convincing because `data.data` is `undefined`. Yesterday, I also create new issue #1149 

Why is this not mentioned and correct in README.md?

Anyway thanks everyone. I am gonna bet for using `react-native-fs` solution.

**Comment by sundariragavan** [comment]
Now i'm using "react-native-fs" for image save to particular folder.
The folder is created and image also saved in destination path but the image is not displayed in **Gallery**.
How to fix the issue.

```const path = `${RNFS.PicturesDirectoryPath}/My Album`;
		await RNFS.mkdir(path);
		return await fetch(uri)
			.then(res => res.blob())
			.then(image => {
				RNFetchBlob.fs.readFile(uri, "base64").then(data => {
					RNFS.appendFile(`${path}/${image.data.name}`, data, "base64").catch(
						err => {
							console.log("error writing to android storage :", err);
						}
					);
				});
			});```

**Comment by n1ru4l** [comment]
@sundariragavan You will have to use CameraRoll api (https://facebook.github.io/react-native/docs/cameraroll.html) to save an image to the camera roll.

**Comment by n1ru4l** [comment]
@sundariragavan Probably my moving the picture there with react-native-fs and then using the destination file uri with as the first param of `CameraRoll.saveToCameraRoll`?

**Comment by sundariragavan** [comment]
@n1ru4l  If i'm use <CameraRoll.saveToCameraRoll>the image is saved in ***DCIM*** folder.

**Comment by elirangoshen** [comment]
i still cannot use it as i'm getting an error : 
Error: ENOENT: no such file or directory, open 'ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001'

im trying from iphone..

**Comment by felipevyg** [comment]
@elirangoshen Did you find a solution for this one?
