### ISSUE TITLE
Add overlay to camera

### ISSUE THREAD

**Issue by MathiasLund** [lwansbrough/react-native-camera#290]
Hi there,

Great repo! 
This is not really an issue, just a question:

Is it possible to add an overlay to the camera?

**Comment by rt2zz** [comment]
@MathiasLund you can do an overlay using normal react-native styling e.g.
```js
<Camera />
<View style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}}>
</View>
```

**Comment by charpeni** [comment]
You can also check the exemple in the PR #304.

**Comment by cwcorbin** [comment]
Is it possible to add multiple overlays, and then capture the video and overlays into a new video?  (That way when it is played in the future, the overlays are a part of the video.)

**Comment by PatchedPixels** [comment]
I am also for looking for the same solution, How to record video with overlay view using react-native, A prompt help would be really appreciated. Thanks

**Comment by storerjeremy** [comment]
@cwcorbin @PatchedPixels Did you guys ever figure out how to record video with an overlay?

**Comment by PatchedPixels** [comment]
We did some prototype work and have idea about how to do it exactly, we now need someone to fund this project for us and we will be more than happy to contribute, we may work even without someone funding but it will be slow that way.

**Comment by PatchedPixels** [comment]
The high level idea is to render using OpenGL when recording the video, we need to render the video by using OpenGL & any overlay objects that are in scene. This needs to be done for Andriod as well as iOS and then those functions can be called through react.

**Comment by PatchedPixels** [comment]
@storerjeremy ^^

**Comment by josegoval** [comment]
> The high level idea is to render using OpenGL when recording the video, we need to render the video by using OpenGL & any overlay objects that are in scene. This needs to be done for Andriod as well as iOS and then those functions can be called through react.

Any real implementation of this?

**Comment by hakeemsyd** [comment]
Any example on how to do this?
