### ISSUE TITLE
libRCTCamera.a is missing

### ISSUE THREAD

**Issue by deanmcpherson** [lwansbrough/react-native-camera#3]
Hey there,

I'm trying to give this a go, but can't find the .a file to add to the build step, I might be missing something though.

**Comment by deanmcpherson** [comment]
Figured it out,

```#import "RCTViewManager.h"```
in RTCCameraManager.h wasn't resolving as the project wasn't searching the react project for header files.

I added ```$(SRCROOT)/../react-native/React``` as a recursive search path in the build settings and it worked like a charm.

**Comment by lwansbrough** [comment]
Oh yeah I forgot to include that step. Thanks for posting the solution.
