### ISSUE TITLE
What's up with the constants?

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#31]
Really a pretty nitpicky thing to make an issue about, I suppose, but stuff like `Camera.constants.CaptureTarget.memory` is not really idiomatic JS. I'm curious as to what the benefits are over simply configuring with a string?

From my experiences in native dev, it seems that the main advantage of enumerables is that the IDE will catch typos in them. This is not the case in JS, and typing an enumerable wrong will have roughly the same effect as typing a string wrong.

**Comment by lwansbrough** [comment]
As per the docs, you can use `Camera.constants.CaptureTarget.memory` or `'memory'`.
