### ISSUE TITLE
How to exit camera mode

### ISSUE THREAD

**Issue by DiegoGallegos4** [lwansbrough/react-native-camera#313]
This is not an issue but how do you close camera window?

Thanks

**Comment by charpeni** [comment]
You can use a navigator to switch between scenes.

https://facebook.github.io/react-native/docs/navigator.html
https://github.com/react-native-simple-router-community/react-native-simple-router
https://github.com/aksonov/react-native-router-flux

**Comment by charpeni** [comment]
I'll close this issue as I think my answer has answered to your question, if not please let me know.
