### ISSUE TITLE
jsSchedulingOverhead (-5999ms) should be positive

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#32]
Get this warning log when using .capture in development mode... I don't know that this is an issue, just FYI

**Comment by lnut101** [comment]
Yes i also saw a lot of this warning, but with different values

**Comment by bright-sea** [comment]
Yes, me too. happened when debug on devices. In index.ios.js, I have set a interval checking like:

<pre>
setInterval(FileSystemUtils.checkInboxFile, 3000);
</pre>

**Comment by lwansbrough** [comment]
@jtremback Is this still happening?

**Comment by pgmemk** [comment]
@lwansbrough Yes it is for me

**Comment by jtremback** [comment]
Haven't seen this myself, for a while.

**Comment by lwansbrough** [comment]
@pgmemk Are you using the latest version of the camera?

**Comment by sunilp** [comment]
What it means is that the start date passed on the timer creation (Date.now() on JavaScript) is 5999ms ahead of the current time on iOS ([NSDate now]), when you're running the app on the device and the executor on your computer it's very unlikely that the times will be the same at the millisecond level. So no, don't worry about it.

can simply ignore.

**Comment by lwansbrough** [comment]
@sunilp That's good news - is there a way we can suppress this notification?
