### ISSUE TITLE
Pattern recognition

### ISSUE THREAD

**Issue by nunziofiore** [lwansbrough/react-native-camera#327]
Is possibile with this component make a behaviour like fb messanger when we see an image like The circle that identify your person to send it to a service? Like a qrcode reader but with circle symbol?

**Comment by lwansbrough** [comment]
I don't see this is a feature of the camera. A module that would do this would likely accept an image (or a stream) as an input, but it wouldn't explicitly be the job of the camera module. There's probably a larger discussion regarding the need to allow modules to communicate with each other to make this process easier.
