### ISSUE TITLE
ReactIOSViewAttributes removed in react-native 0.4.3

### ISSUE THREAD

**Issue by VonD** [lwansbrough/react-native-camera#33]
The changelog mentions that [requireNativeComponent](https://github.com/facebook/react-native/blob/v0.4.3/Libraries/ReactIOS/requireNativeComponent.js) should be used instead : 
https://github.com/facebook/react-native/releases/tag/v0.4.3

**Comment by dhrrgn** [comment]
Added PR for this here: https://github.com/lwansbrough/react-native-camera/pull/34
