### ISSUE TITLE
data.path is always null

### ISSUE THREAD

**Issue by Thomsos** [lwansbrough/react-native-camera#343]
### Steps to reproduce
1. Press button to call capture method

### Expected behaviour
Return {path: 'file\\...."}

### Actual behaviour
Path is null.

### Environment
- **Node.js version**: 6.2.2
- **React Native version**: 0.28.0
- **React Native platform + platform version**:  Android 6.0

### react-native-camera
**Version**:  0.3.8

**Comment by Thomsos** [comment]
Solved my own problem by adding:

`<uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-feature android:name="android.hardware.camera" android:required="false"/>
  <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>`

To:  `android/app/src/main/AndroidManifest.xml `

I would recommend updating the docs to show this in the manual install.

**Comment by anton6** [comment]
In addition I also had to add: captureTarget={Camera.constants.CaptureTarget.disk} to Camera component.

**Comment by mike-aungsan** [comment]
I have the same problem on Android 4.4, Device S4. Any help?
