### ISSUE TITLE
iOS: captureQuality "photo" takes first capture out of focus

### ISSUE THREAD

**Issue by ronaldheft** [lwansbrough/react-native-camera#348]
### Steps to reproduce
1. Set capture quality to "photo"
2. Render <Camera>
3. Trigger "capture" and keep `<Camera>` element rendered
4. Observe captured image is out of focus
5. Trigger "capture" again
6. Observe second and all future captured images are in focus

### Expected behaviour
The capture event should occur after the camera is done auto-focusing on all captures.

### Actual behaviour
The capture event appears to be capturing the image slightly before auto-focus is complete on the first capture.

### Additional information
This is not a problem on Android or when captureQuality of "high", "medium", "low" is used. 

### Environment
- **React Native version**: v0.29.x
- **React Native platform + platform version**: iOS 8.x

### react-native-camera
**Version**: "master"

**Comment by charpeni** [comment]
It should be fixed by #322, please let me know if not.
