### ISSUE TITLE
Avoid asking for microphone permission

### ISSUE THREAD

**Issue by vinayr** [lwansbrough/react-native-camera#366]
I am using this module for QR code scanning. My app doesn't need microphone access. How can I have this module not to ask for microphone access?

This issue has been raised before(#205) and I have tried setting `captureAudio={false}` but still it asks for microphone access.

**Comment by vinayr** [comment]
I forked and disabled logic related to `requestAccessForMediaType: AVMediaTypeAudio`

**Comment by ataomega** [comment]
Could you please share details on how to remove microphone access request?

**Comment by vinayr** [comment]
@ataomega actually `captureAudio={false}` works. I was using an old fork of this module which did not have `captureAudio`. Now I just use the master branch with `captureAudio={false}` parameter.

**Comment by ataomega** [comment]
Thanks for your answer. may i ask where should i put it? in react native file when i'm calling it or should i edit react-native-camera's project files?

Thanks in advance!

**Comment by vinayr** [comment]
In your react-native file. Example -
```
<Camera
  captureAudio={false}
  style={styles.camera}
  .....
  .....
/>
```

**Comment by ataomega** [comment]
Thanks

**Comment by HarshitMadhav** [comment]
@vinayr  you said you did something like this 
I forked and disabled logic related to `requestAccessForMediaType: AVMediaTypeAudio `

can you explain a bit?
