### ISSUE TITLE
Getting Started is not clear 

### ISSUE THREAD

**Issue by voronianski** [lwansbrough/react-native-camera#4]
> In XCode, right click Libraries and Add Files to ______
 Add libRCTCamera.a to Build Phases -> Link Binary With Libraries

Where is `libRCTCamera.a`?

**Comment by voronianski** [comment]
@lwansbrough ok.. I get it working:

1. `npm install react-native-camera --save`
2. In XCode, right click Libraries ➜ `Add Files to ______`
3. Go to `node_module` ➜ `react-native-camera` and add `RCTCamera.xcodeproj`
4. Add `libRCTCamera.a` (it's in workspace) to `Build Phases` ➜ `Link Binary With Libraries`
5. Run (`Cmd+R`)

I leave this open if somebody will be stuck too.

**Comment by lwansbrough** [comment]
Thanks, this is more thorough, I'm going to add it to the readme.
