### ISSUE TITLE
Update dependencies for Latest React Native (0.5.0)

### ISSUE THREAD

**Issue by rpastorelle** [lwansbrough/react-native-camera#42]
If there's nothing in the latest react native (0.5.0) that prevents this from working, can you please bump the dependency requirement? Thanks!

---

When trying to update to RN 0.5.0 got the following:

```
npm ERR! peerinvalid Peer react-native-camera@0.2.9 wants react-native@^0.4.3
```

**Comment by lwansbrough** [comment]
Yeah sure. Ah sorry I would have been quicker to do this if I realized npm was throwing an error.

**Comment by rpastorelle** [comment]
@lwansbrough Thanks!
