### ISSUE TITLE
Cloning Project, Running Example Doesn't Work in Xcode 8

### ISSUE THREAD

**Issue by timcamber** [lwansbrough/react-native-camera#421]
### Steps to reproduce
1. Clone project
2. Follow instructions in `Example/README.md`
3. Run project in Xcode 8
### Expected behaviour

Example app should run in Xcode 8
### Actual behaviour

Build errors occur when trying to build in Xcode 8
### Environment
- **Node.js version**: `6.5.0`
- **React Native version**: `0.26.3`
- **React Native platform + platform version**: iOS `10.0.2 (14A456)`, Xcode `8.0 (8A218a)`
### react-native-camera

**Version**: on `master`, commit `1747ec4b0a52472cf2e8ad95f2c3603595e28e13`

**Comment by charpeni** [comment]
Thank you for reporting, i'm working on this right now.

**Comment by atinder90** [comment]
In my case build errors are gone after updating react and react-native but app crashed while rendering <Camera />
Using Xcode 8

**Comment by getnashty** [comment]
+1 @atinder90

**Comment by royisch** [comment]
@charpeni - any updates? my app stopped working with the camera once i upgaraded xcode. i get EXC_BAD_ACCESS once accessing the camera

**Comment by muratozgul** [comment]
see #386 (nitrog7's answer solved my issue)
