### ISSUE TITLE
Why the 0.5.0 peerDependency?

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#43]
This no longer works with `react-native` master. Is it really necessary? I have gone back down to `0.2.9` in the mean time.

**Comment by rt2zz** [comment]
While react-native is moving so fast I think it would be best to support a liberal range of versions. e.g. `>0.4.2`rather than fixing it on a minor version

**Comment by lwansbrough** [comment]
Sorry I sort of botched that change. Fixed in 0.2.11, supporting `>=0.4.3`. Thanks for bringing this to my attention.
