### ISSUE TITLE
Helping writing onBarCodeRead function

### ISSUE THREAD

**Issue by Talkwondo** [lwansbrough/react-native-camera#435]
Hello,
I tried to make a qr code reader based react-native camera.
the camera is open and i did a rectangular. just need the function of scanning and output the link. or maybe navigate to a page in the app.

Many Thanks,

**Comment by comountainclimber** [comment]
look here for a good example https://github.com/lazaronixon/react-native-qrcode-reader

**Comment by duhaime** [comment]
@lwansbrough it's probably safe to close this issue...
