### ISSUE TITLE
Save dummy image when in the simulator

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#46]
This will allow much faster development for me. I'm going to dive in and try to make this work, let me know if there have been previous attempts!

**Comment by jtremback** [comment]
https://github.com/lwansbrough/react-native-camera/pull/47

**Comment by jtremback** [comment]
This has mysteriously disappeared. Why?

**Comment by lwansbrough** [comment]
I think you fixed this?
