### ISSUE TITLE
Camera freezed on iOS 9.0

### ISSUE THREAD

**Issue by apFlex** [lwansbrough/react-native-camera#462]
While opening for the third time the Camera View, it looks to be freezed.
### Environment
- **Node.js version**:  v4.6.0
- **React Native version**:  0.35.0
- **Platform version**: iOS 9.0
### react-native-camera

**Version**:  "master"

**Comment by freshlybakedcode** [comment]
I also have this issue, although I've only tried it in the iOS9 simulator; are you seeing the same problem on the actual hardware?

**Comment by apFlex** [comment]
I've tried on hardware finally. It seems to not freeze anymore, I've tested it on iOS 8.0 and iOS 10.0 only.

**Comment by freshlybakedcode** [comment]
@apFlex Ah, that's awesome news - I'm pleased to hear it! :)
