### ISSUE TITLE
.mov Upload to Server Not Returning full length of video

### ISSUE THREAD

**Issue by rajinwonderland** [lwansbrough/react-native-camera#467]
### Steps to reproduce
1.  Capturing video on component via: 
captureTarget: Camera.constants.CaptureTarget.cameraRoll,
captureMode: Camera.constants.CaptureMode.video,

2. Capturing path from this.camera.capture().then(data)=> {
const file = {
   path: data.path,
   name: myvideo.mov,
   type: video/quicktime
}
...

3. Uploading file via RNS3 component (react-native-aws3)

### Expected behaviour
Pushes full length of video to server.
AWS returns full length of video.

### Actual behaviour
Returning a <00:01 video with a single frame.

### Environment
- **Node.js version**: nodejs v6.3.0 
- **React Native version**: react-native v0.34.1
- **React Native platform + platform version**: iOS 10.0, Android 6.0

### react-native-camera
**Version**: v0.3.9

**Comment by callmephilip** [comment]
@rajinwonderland seeing the same exact issue here. did you manage to get to the bottom of this?
