### ISSUE TITLE
v0.4.0

### ISSUE THREAD

**Issue by rt2zz** [lwansbrough/react-native-camera#483]
@charpeni awesome work with the latest round of updates! should I cut v0.4.0 now?

I figure its time we get back to shipping consistent pinnable versions. This is not a commitment to being bug free, but at least we can start establishing consistency.

**Comment by charpeni** [comment]
Sure, let's do this. :)

**Comment by rt2zz** [comment]
https://github.com/lwansbrough/react-native-camera/releases/tag/v0.4.0
