### ISSUE TITLE
Continuing PeerDependency issues.

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#50]
Trying to install with react-native `0.6.0-rc` still causes a peerDependency error.

**Comment by jtremback** [comment]
There's significant debate about whether peerDependencies should have been added to npm in the first place. I would vote for eliminating it.

**Comment by mrspeaker** [comment]
Is there any way to work around this?

**Comment by lwansbrough** [comment]
I can eliminate this. Should I just not include any reference to react-native?

**Comment by jtremback** [comment]
You can list the version as `*`, and I think it will be OK.
