### ISSUE TITLE
use arrow functions instead of .bind in your exapmle 

### ISSUE THREAD

**Issue by Kottidev** [lwansbrough/react-native-camera#506]
takePicture = () => { }

startRecording = () => {

stopRecording = () => { }

and remove 

this.takePicture = this.takePicture.bind(this);
this.startRecording = this.startRecording.bind(this);
this.stopRecording = this.stopRecording.bind(this);
this.switchType = this.switchType.bind(this);
 this.switchFlash = this.switchFlash.bind(this);

from constructor

take a look on this guide https://babeljs.io/blog/2015/06/07/react-on-es6-plus

**Comment by sibelius** [comment]
@Kottidev could u send a PR for this?

**Comment by desmondhume** [comment]
@sibelius I just opened a PR for this. 

PS. Thank you @Kottidev I didn't know this tip, lots of less lines of code!
