### ISSUE TITLE
When I try to run the example I get a critical error: Unhandled JS Exception: Invariant Violation: Module name prefixes should've been stripped by the native side but wasn't for RCTJSCExecutor 

### ISSUE THREAD

**Issue by idvorkin** [lwansbrough/react-native-camera#514]
### Steps to reproduce
1. npm install 
2. Execute from xcode

### Expected behaviour
Sample app runs

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/280981/21196545/d8c22ca6-c1ec-11e6-984e-b939e06c6fc6.png)

### Environment
- **Node.js version**: v7.2.0
- **React Native version**: 0.34.1
- **React Native platform + platform version**: iOS 10 simulator

### react-native-camera
**Version**: master

**Comment by desmondhume** [comment]
@idvorkin I solved this by just restarting react native packager.

**Comment by idvorkin** [comment]
Hymn, my repro also went away. Closing for now...
