### ISSUE TITLE
Getting Error in Build regarding Permission last Commit 

### ISSUE THREAD

**Issue by joypatel04** [lwansbrough/react-native-camera#515]
### Actual behaviour
Getting Error in Build 

<img width="1431" alt="screen shot 2016-12-14 at 12 37 02 pm" src="https://cloud.githubusercontent.com/assets/18585502/21199857/11132d78-c1fa-11e6-9eb2-271db4204ae2.png">

Looks like something to do with Permission.
But Since i am on react-native 0.34 i don't know how i can resolve it

### Environment
- **Node.js version**: v7.2.1
- **React Native version**:  0.34.1
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**:  "master"

**Comment by iandea** [comment]
Seeing the same here.  RN Version 0.38

**Comment by joypatel04** [comment]
Looks like we have to use http://facebook.github.io/react-native/docs/permissionsandroid.html 
@iandea

**Comment by charpeni** [comment]
Sorry, it should be fixed now.

**Comment by joypatel04** [comment]
Thanks @charpeni
