### ISSUE TITLE
App stops when I try to capture an image.

### ISSUE THREAD

**Issue by ansierras** [lwansbrough/react-native-camera#539]
### Steps to reproduce
1. Open Camera App
2. Try to capture image
3.

### Expected behaviour
The app should take a picture and console log the result.

### Actual behaviour
The app stops (not crashes) at a thread stop that says" __abort_with_payload".
I try to continue program execution, but it still stops.
I have tried using low quality picture capture, but the problem persists. 
### Environment
- **Node.js version**: latest
- **React Native version**: latest
- **React Native platform + platform version**: iOS

### react-native-camera
**Version**: npm version

**Comment by hugohow** [comment]
I have the same issue !

**Comment by ansierras** [comment]
Can you tell me how you solved it?

**Comment by hugohow** [comment]
In my Info.plist, I added this, and it works : 

```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>

<!-- Include this only if you are planning to use the camera roll -->
<key>NSPhotoLibraryUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>

<!-- Include this only if you are planning to use the microphone for video recording -->
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microsphone is accessed for the first time</string>
```

**Comment by ansierras** [comment]
This doesn't solve the issue for me :(

**Comment by RikNieuwoudt** [comment]
I'm also having this issue.

**Comment by hudjoubert** [comment]
This info.plist is only for iphone or i have to do this on android too?

**Comment by julesmoretti** [comment]
I had the same issue on iOS until I allowed access to camera roll.

```
  <!-- Include this only if you are planning to use the camera roll -->
  <key>NSPhotoLibraryUsageDescription</key>
  <string>Your message to user when the photo library is accessed for the first time</string>
```

**Comment by ansierras** [comment]
Thank you @julesmoretti ! That solved my issue. I was only accessing the camera in the info.plist, not the camera roll. I added access to the camera roll and now it works perfectly. 
Thanks a lot!
