### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by nonameolsson** [lwansbrough/react-native-camera#549]
It would be really nice with a changelog for each new release.

**Comment by sibelius** [comment]
can we use git releases for this?

**Comment by piuccio** [comment]
would be really sweet if this page had the release notes of each version https://github.com/lwansbrough/react-native-camera/releases

Every time there's an update I have to go through the commit logs and try to figure out what changed

**Comment by sibelius** [comment]
we gonna come up with something on this issue https://github.com/lwansbrough/react-native-camera/issues/246#issuecomment-350577509
