### ISSUE TITLE
Add GPS metadata to image. (needs docs)

### ISSUE THREAD

**Issue by jtremback** [lwansbrough/react-native-camera#56]
Might be problematic, because of the need to import the location framework. Will investigate whether this should be in this module etc.

**Comment by jtremback** [comment]
Probably going to do this as an optional parameter that one can pass to `.capture`. Seems kind of weird semantically, but the react native geolocation polyfill is too good not to use.

**Comment by jtremback** [comment]
Might be good to actually have that parameter just be general metadata.... or maybe pass it via props?

**Comment by jtremback** [comment]
Adding GPS metadata here: https://gist.github.com/jtremback/e5dde527da9bcd69536e

I still need to sort out some merging stuff with the latest version tomorrow. @lwansbrough you may want to bump the version that is on npm to the latest.

**Comment by lwansbrough** [comment]
https://github.com/lwansbrough/react-native-camera/commit/8eb6e9e7dce7d70b9be60a70515a7b972f9a8a40

**Comment by baseio** [comment]
Hi, sorry for writing to a closed issue - but some additional documentation/examplecode on the "pass a location object from the geolocation api" would be helpful...
Thanks in advance!

**Comment by lwansbrough** [comment]
@jtremback? I personally haven't done this.

**Comment by jtremback** [comment]
Sure, I'll take care of it.

**Comment by jtremback** [comment]
Does this clear things up? 00a2b3adaf3df877da75181e5889664dbd4033b7

**Comment by RikNieuwoudt** [comment]
Hi, I still can't figure out how to add meta data to an image.
If we use the example on the Usage section on the repo homepage:
`  takePicture() {
    this.camera.capture()
      .then((data) => console.log(data))
      .catch(err => console.error(err));
  }`

Where and how do I add the meta data?

**Comment by npomfret** [comment]
hi - i've submitted a PR which I think fixes this on iOS (android to follow).

The way to use it is to something like:

  async _takePicture() {
      const options = {};
      if (this.state.position) {
        // position comes from: navigator.geolocation.watchPosition((position) => this.setState({position}))
        options.location = this.state.position;
      }
      const data = await this._camera.capture(options);
  }


Then when you use RN CameraRoll to retrieve the image it has the location info attached.  I'm looking for someone to help test my PR.  If you have any time it would be appreciated.

https://github.com/lwansbrough/react-native-camera/pull/635

**Comment by koswarabilly** [comment]
@npomfret have android version been fixed? because i need to pass metadata to images
