### ISSUE TITLE
undefined is not an object (evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by subhash8108** [lwansbrough/react-native-camera#584]
I  have simple react native run from my emulator, and your plugin (component) install successfully, but one function not push on my code. 

please find attached file.
![camera_error](https://cloud.githubusercontent.com/assets/542535/22595169/42e49fe2-ea4c-11e6-859b-118590f50520.png)

Please help me... how to resolved this issue.
I'm waiting your reply.

Thanks
Subhash

**Comment by gustarus** [comment]
Same problem I've got today 😭.

**Comment by gustarus** [comment]
Resolved: `react-native link react-native-camera` one more time.

**Comment by ptomasroos** [comment]
Should we close, is the workaround working?

**Comment by AlisonWonderlandApps** [comment]
I have the same error

**Comment by ptomasroos** [comment]
Then I will close. Thanks!

**Comment by trops** [comment]
I linked and info.plist doesn't have Camera permissions. Just installed first time today. 
"Cannot read property "Aspect" of undefined from example code.

**Comment by yinoneliraz** [comment]
Can you please write steps to solve this in a more elaborated way?

**Comment by muhlucas** [comment]
I had same issue
My solution was react-native link react-native-camera put Camera permission on info.plist 
And recompile react native run-ios

**Comment by matthieucan** [comment]
On Android, uninstalling and reinstalling the apk worked for me.

**Comment by rcorrie** [comment]
The key for me on iOS was

```
rm -rf ./node_modules
npm install
watchman watch-del-all
```

then I shut down packager, quit simulator, then `react-native run-ios`

**Comment by mashwinprdxn** [comment]
In case anyone's facing this issue on Android, please try the [gradle upgrade guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md). It worked for me.
