### ISSUE TITLE
How can i make the <Camera/> round?

### ISSUE THREAD

**Issue by MagicalYan** [lwansbrough/react-native-camera#636]
The Camera is square, and style's borderRadius is unuseful, how can i hide the corner?

**Comment by MagicalYan** [comment]
I'm stupid, set  overflow:'hidden' can hide the corner.

**Comment by stinodes** [comment]
@yansaid Did you use this for Android as well? If so, can you post a short example? I can't seem to get the corners rounded in my app.

**Comment by yansaid** [comment]
@stinodes Sorry, i only test this for iOS.

**Comment by stinodes** [comment]
Alright, thanks for responding this soon. I guess it's​ an android limitation then.

**Comment by sunweiyang** [comment]
@stinodes, don't know if you already solved it, but you can surround the `Camera` component with an `View` and edit the `View` component's styles (`borderRadius` and `overflow`).
