### ISSUE TITLE
What type of bar codes can be read?

### ISSUE THREAD

**Issue by nraboy** [lwansbrough/react-native-camera#64]
I'm sorry if this is an inappropriate place to ask, but what types of bar codes can be read with this component?  Maybe you can add them to the README?

Thanks,

**Comment by jtremback** [comment]
I've never used the barcode functionality, but I saw this in the source:

```
           @"BarCodeType": @{
               @"upce": AVMetadataObjectTypeUPCECode,
               @"code39": AVMetadataObjectTypeCode39Code,
               @"code39mod43": AVMetadataObjectTypeCode39Mod43Code,
               @"ean13": AVMetadataObjectTypeEAN13Code,
               @"ean8":  AVMetadataObjectTypeEAN8Code,
               @"code93": AVMetadataObjectTypeCode93Code,
               @"code138": AVMetadataObjectTypeCode128Code,
               @"pdf417": AVMetadataObjectTypePDF417Code,
               @"qr": AVMetadataObjectTypeQRCode,
               @"aztec": AVMetadataObjectTypeAztecCode
               },
```

**Comment by nraboy** [comment]
Awesome.  Thanks for finding this for me @jtremback :-)

**Comment by lwansbrough** [comment]
@nraboy Yeah that's the list, also the scan event will return the type of barcode recognized.

**Comment by liukepeng** [comment]
I want to  implement  scan QR_Code with React Native for Android.Can you help me?

**Comment by lwansbrough** [comment]
@liukepeng Android is not yet supported unfortunately.

**Comment by liukepeng** [comment]
Thank you very much!
