### ISSUE TITLE
Long pause immediately after Camera initializes

### ISSUE THREAD

**Issue by achang28** [lwansbrough/react-native-camera#68]
When rendering the react-native-camera module, the app locks up for about 15 seconds before I can interact with the app.  Can't scroll; can't navigate anywhere, etc.  Seems like a case of locking the UI thread.  Anyway, after the 15 seconds, the camera works fine.

**Comment by lwansbrough** [comment]
@achang28 Thanks for reporting this, I haven't experienced this but I'm going to look into it tomorrow.

**Comment by lwansbrough** [comment]
So I saw and replied to your pull request, waiting for your thoughts. In the mean time, here's something I'm proposing. This fixed UI lock up for me, let me know if it works for you.

https://github.com/lwansbrough/react-native-camera/tree/performance-improvements

**Comment by achang28** [comment]
Caused a crash (in Xcode) when I unmounted react-native-camera module.  See attached image.

So I Downloaded everything from "performance-improvements" branch, and restarted everything (Xcode, and  terminal instance running Node (iojs v2.3.4)).
<img width="976" alt="screen shot 2015-07-19 at 1 28 21 pm" src="https://cloud.githubusercontent.com/assets/3760499/8767845/a97bcd70-2e1e-11e5-944a-05c22ea58895.png">

**Comment by lwansbrough** [comment]
@achang28 Try moving line 97 to before the super call on line 95 and report back.

**Comment by achang28** [comment]
oh Damn!  Just retried the app about 15x (e.g. relaunched in Xcode).  Works like a charm!  Awesome shit!  I'll keep playing around with it, but it has been working consistently with "only" a 0.5 second delay after rendering the react-native-camera module.  Consistent 0.5 second delay beats 15 seconds any day!!!

**Comment by lwansbrough** [comment]
Ok cool, that's good to hear. I think I'll merge this with master then push to npm.

**Comment by achang28** [comment]
Merge it!

**Comment by achang28** [comment]
looks like your suggested change of ```[self.manager stopSession]``` above ```[super removeFromSuperview]``` didn't make it through w/ 0.3.1.  In RCTCamera.m, around line 95

**Comment by lwansbrough** [comment]
Oh sorry, I guess that wasn't clear. This change is needed to fix the problems you mentioned?

**Comment by achang28** [comment]
Yeah.  Specifically the app crashing that occurs when unmounting Camera module.

**Comment by lwansbrough** [comment]
My bad, `0.3.2` published to accommodate these changes.

**Comment by achang28** [comment]
Hot like buttah.  Good shit.  Works beautifully.

**Comment by lwansbrough** [comment]
👍
