### ISSUE TITLE
No Audio ?

### ISSUE THREAD

**Issue by sunilp** [lwansbrough/react-native-camera#69]
Tried implementing with, Video get recorded, but audio, tried with different devices, still same issue. 
Also, it never asks the permission to use microphone.

**Comment by lwansbrough** [comment]
Should be resolved, sorry about this. Pull the latest version (`0.3.1`) from npm.

**Comment by lwansbrough** [comment]
@sunilp There's a small possibility this isn't fixed.. I'm looking into it. Let me know if you continue to experience problems.

**Comment by sunilp** [comment]
yeah :+1:  works perfectly now. Thanks!!
