### ISSUE TITLE
Add QRCodeReaderViewController support

### ISSUE THREAD

**Issue by developerworks** [lwansbrough/react-native-camera#7]
I am not a professional ios programmer, If you can support the qr code reading, that's very nice. I think it must be useful for many apps, and will be very welcome. 

https://github.com/yannickl/QRCodeReaderViewController

**Comment by lazaronixon** [comment]
:+1:

**Comment by lwansbrough** [comment]
https://github.com/lwansbrough/react-native-camera/commit/60fe613bd1ad2ad8efca3d22e5219d173eabd6ef
