### ISSUE TITLE
how to get video thumbnail

### ISSUE THREAD

**Issue by Symous** [lwansbrough/react-native-camera#700]
Actually,I have slove this by myself. I leave this issue here to help any other who are looking for the solution. :-)

it's a surprise for me to find that if we **put a video uri**(such as video generated by react-native-camera) **to Image** of react-native component, **it will show us a thumbnail of the video automatically**.
```
<Image source={{uri : this.state.videoUri}} />
```

**Comment by abologna-r7** [comment]
Nice, never thought about it...

**Comment by abologna-r7** [comment]
@Symous Any special styling that needs to be applied to the Image component? Even though I use an image with a URI, ex: 'https://cdn.com/video.mp4') I'm still getting a no thumbnail.

**Comment by Symous** [comment]
@abologna-r7 nothing special , but if you are trying to load a video on Internet  , I guess that it will need time to load thevideo? I am using this way to show  thumbnail of a local video.

**Comment by checkitoutteam** [comment]
@abologna-r7  me too, it doesn't work. I got the following error:
`Error decoding image data <NSData 0x7fc2cb34dec0; 2516731 bytes>`
@Symous How did you manage it? Did you had a prefix or so?
Thanks!

**Comment by danielreis1** [comment]
use uri:'file:///path_to_image'

**Comment by samanthacampisi** [comment]
I've tried this and found out that this only works in Android for me. No luck in iOS.

**Comment by ckalpit** [comment]
same here, on android it works fine, but on iOS it doesn't work.

**Comment by dinatazy** [comment]
in my case this works only on iOS

**Comment by timt** [comment]
You could use this library to make a thumbnail image: https://github.com/phuochau/react-native-thumbnail

**Comment by sibelius** [comment]
do u think we can add this to the docs?

**Comment by sibelius** [comment]
please add here https://github.com/react-native-community/react-native-camera/blob/master/docs/Recipes

**Comment by leonyhenn** [comment]
what library did u guys use to get the url? in my case i used React Native CameraRoll on Android which returns file path as content://media/external/video/media/7086, but it doesnt show thumbnail when i plug in the file path as source uri. @Symous

**Comment by asimkhan0** [comment]
@leonyhenn did you find any solution ? 
CameraRoll returns URIs 'content://media/external/video/media/11' and I need to display an Image/Thumbnail of it.

**Comment by n1ru4l** [comment]
@leonyhenn @asimkhan0 Like @timt mentioned: https://github.com/phuochau/react-native-thumbnail

**Comment by hungdev** [comment]
https://github.com/hungdev/react-native-media-helper
