### ISSUE TITLE
captureTarget disk, memory management

### ISSUE THREAD

**Issue by Amerr** [lwansbrough/react-native-camera#702]
Does saving file on disk using ***Camera.constants.CaptureTarget.disk***  saves temp or permananently and do we need to manually delete those files are is it handled automatically. 

i just need to know the lifecycle of the image or video saved in the disk. Thanks

**Comment by npomfret** [comment]
I don't believe they are deleted in either implementation.  If you need them to be deleted you have to do that yourself.

**Comment by Okipa** [comment]
+1, the images are stored until you delete them (with https://github.com/itinance/react-native-fs for example) or until you remove your app.

**Comment by Amerr** [comment]
@Okipa  so whenever i rebuild the app , the files that are  created by app will be automatically flushed out. correct me if i'm wrong.

**Comment by Okipa** [comment]
Nope, unless I'm wrong (^^) the app is not considered as removed and reinstalled when you rebuild.
Your preferenced are saved (permissions, remote debug, etc) and your files are kept.

**Comment by Amerr** [comment]
@Okipa  thanks, i have checked it. the files are not deleted. i have to manually delete it

**Comment by kodatech** [comment]
Hi @Amerr ! Could you please tell us where did you find the files? I'm just using as a barcode scanner but I'm not sure if something is stored and where? thanks

**Comment by Amerr** [comment]
@kodatech  i used [React native fetch blob](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#dirs), to access file system and used ***dirs.DocumentDir*** to list all saved files.

**Comment by kodatech** [comment]
Thanks @Amerr for your answer. I'm just using the barcode scanner and looks like it is not storing any image at all. Only if I use the method capture: `await this.refs.camera.capture().then((obj) => {
      console.log(obj.path)
    })` an image is stored, otherwise looks like nothing's happening.

**Comment by checkitoutteam** [comment]
Hey! I'm not sure, all my data are deleted when I install a newer version of my app from the App Store. Any idea? Thanks a lot
