### ISSUE TITLE
Camera crashes in Simulator; but works in actual device

### ISSUE THREAD

**Issue by achang28** [lwansbrough/react-native-camera#71]
Looks like we caused brought on an unintended-consequence going back to https://github.com/lwansbrough/react-native-camera/issues/68.

As the Camera module is in the middle of rendering, something with the obj-c code crashes
![screen shot 2015-07-20 at 2 56 02 pm](https://cloud.githubusercontent.com/assets/3760499/8788494/b0e0d278-2eef-11e5-8d39-a7bfe3900df6.png)

**Comment by lwansbrough** [comment]
Ah oops. Should be an easy fix.
