### ISSUE TITLE
Undefined is not an object (evaluating CameraManager.Aspect)

### ISSUE THREAD

**Issue by joshterrill** [lwansbrough/react-native-camera#712]
I am trying to create the sample app using `react-native init`. I get this error:

`undefined is not an object (evaluating 'CameraManager.Aspect')`

```
react-native-cli: 1.0.0
react-native: 0.44.0
node: 7.5.0
npm: 4.1.2
xcode: 8.3.2
emulator: iPhone 6, IOS 10.3
```

Screenshot: 

![Imgur](http://i.imgur.com/Kci3Fqd.png)

Anyone know what I can do to get this to work?

**Comment by wookiem** [comment]
Did follow the `manual` iOS installation steps?  The `mostly automatic install with react-native` for iOS doesn't seem to do all of the manual steps.

**Comment by ugiacoman** [comment]
Did you `react-native link`?

**Comment by joshterrill** [comment]
Yes, I ran `react-native link` and it said linked successfully. I guess I'll try doing the manual steps today.

**Comment by colewinans** [comment]
I'm experiencing the same, with the same setup.

**Comment by colewinans** [comment]
@joshterrill I experienced the same issue. Try killing the simulator, and launching it again with `react-native run-ios`. This solved it for me.

**Comment by ccuilla** [comment]
I had this issue on Android. iOS was running fine w/out running `react-native link react-native-camera`. Once I ran that command, now the iOS build fails with `React/RCTBridge.h not found`.

**Comment by colewinans** [comment]
@ccuilla Which version of React Native are you using? [Looks like header files were moved in 0.4.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)

**Comment by ccuilla** [comment]
@colewinans Hey Cole! We're using RN 0.43. From what I can tell, react-native-camera 0.9 was installed (through `npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save`). I'm resetting and trying again.

**Comment by jaredtmartin** [comment]
Same issue.  Any fix?

**Comment by ccuilla** [comment]
What finally worked for me was to use the Pods install for iOS and the manual install for Android.

**Comment by flyingpig2016** [comment]
How to manual install for android？

**Comment by JohnHour89** [comment]
How to use the Pods install for iOS???

**Comment by Ektasahu0027** [comment]
In ANDROID i have same problem but i resolve it.... i just close my packager and and also uninstall the app and than start packager again and run the command react-native run-android after that may app working properly

**Comment by sebgam** [comment]
I have the same problem in ios but when I run it in a real device it works perfectly

**Comment by irfanismaya20** [comment]
still Error in Android

**Comment by mashwinprdxn** [comment]
In case anyone's facing this issue on Android, please try the [gradle upgrade guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md). It worked for me.

**Comment by tomderudderetna** [comment]
still Error in Android

**Comment by n1ru4l** [comment]
Duplicate of #2088

Please link properly or provide a reproduction repository.
