### ISSUE TITLE
'Camera' has no propType for native prop 'RCTCamera.testID' of native type 'String'

### ISSUE THREAD

**Issue by LEEY19** [lwansbrough/react-native-camera#717]
Have been using react native camera without issue, but when i set up my project in a new local machine by git cloning my existing project, this appears. This screen appears after app is finished transform on react packager. Need some opinions.

![screenshot_2017-05-24-11-29-01](https://cloud.githubusercontent.com/assets/20885778/26385801/a609702e-4074-11e7-8f64-bd7abb84a438.png)

### Environment
- **React Native version**:
v0.40
- platform version**: Android 5.0

### react-native-camera
Followed READme on installation

**Comment by npomfret** [comment]
Thanks for this.  Can you test this [PR](https://github.com/lwansbrough/react-native-camera/pull/718) to see if it fixes the problem?

**Comment by Julesfpollender** [comment]
@npomfret PR #718 fixed the issue for me. Thanks!

**Comment by RUIFERNANDE5** [comment]
@npomfret I also experienced this issue 

"dependencies": {
    "react-native": "0.42.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
   ....
}
android device 7.0

#718 fixed it for me too!

**Comment by npomfret** [comment]
@Julesfpollender @RUIFERNANDE5 many thanks for testing the PR.  I've merged it as a result of your confirmations - cheers!
