### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by darkrishabh** [lwansbrough/react-native-camera#73]
how can we set image quality as for video, a hd video of 20 sec is over 50mb which is not something you want to upload from your data plan.

**Comment by darkrishabh** [comment]
I will be making a PR for that, since its not there and a camera plugin should have this. :)

**Comment by lwansbrough** [comment]
Having that discussion here I believe. Noted, I'll try and figure something out ASAP.

**Comment by lwansbrough** [comment]
Oops, forgot the link: https://github.com/lwansbrough/react-native-camera/issues/65

**Comment by darkrishabh** [comment]
I did try something but what it was pretty unusual. It worked good for the first time but taking a videos back to back raised error during save

BTW I have react-native-cameraIOS repo which uses SCrecorder and give alot of additional features. you can check it out. It provides filter also. I think it can be a great library to help us throughout. I pulled it from react-native screcorder and fixed few things as it was quite inactive there. Have a look at that and also the screcorder library for objective c

**Comment by lwansbrough** [comment]
@darkrishabh We've decided not to rely on third party libraries at this time due to the complexity of managing third party dependencies.

**Comment by jtremback** [comment]
@darkrishabh SCRecorder looks pretty full featured, perhaps you can just wrap that and use it in your app without involving this module.

**Comment by darkrishabh** [comment]
Yeah that what I am doing over here https://github.com/darkrishabh/react-native-cameraIOS
