### ISSUE TITLE
Camera stays open when device is locked (android)

### ISSUE THREAD

**Issue by chronixlo** [lwansbrough/react-native-camera#738]
Locking the device while the app is in foreground doesn't kill the camera.
Can be observed in Android device monitor or device's App use details.

Should this be handled with AppState eventListeners or something else?

Android: 6.0
rn: 0.44.1
rn-camera: 0.9

**Comment by mikaello** [comment]
Related to issue #556, #460 and #263

**Comment by chronixlo** [comment]
Thanks, didn't find those earlier. AppState works for my usecase.
