### ISSUE TITLE
Whole day gone! FTW with android video recorder?

### ISSUE THREAD

**Issue by ramneekhanda** [lwansbrough/react-native-camera#752]
Help please!
I have trying switching to various build tools, sdks, simulators.. 
Video recoding wont work..

Does anyone have it working? Any guesses on what i could be doing wrong?

06-15 01:43:06.418  1685  7434 I NuPlayerDecoder: [OMX.google.vorbis.decoder] resubmitting CSD
06-15 01:43:06.418  1685  7434 I NuPlayerDecoder: [OMX.google.vorbis.decoder] resubmitting CSD
06-15 01:43:06.418  7292  7292 E RCTCameraModule: Media recorder stop error.
06-15 01:43:06.418  7292  7292 E RCTCameraModule: java.lang.RuntimeException: stop failed.
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at android.media.MediaRecorder.stop(Native Method)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at com.lwansbrough.RCTCamera.RCTCameraModule.releaseMediaRecorder(RCTCameraModule.java:386)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at com.lwansbrough.RCTCamera.RCTCameraModule.onError(RCTCameraModule.java:130)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1029)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at android.os.Looper.loop(Looper.java:148)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-15 01:43:06.418  7292  7292 E RCTCameraModule: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rt2zz** [comment]
not sure but i can recommend
- try a few different devices
- check the issue queue to see if others have the same problem

I know video recording has worked in the past for android so you may have a device bug, or a dependency issue.

**Comment by ramneekhanda** [comment]
![vid_20170615_021314](https://user-images.githubusercontent.com/1538416/27147826-c79c7f80-5170-11e7-99a8-3e5c83ee093b.gif)

Finally got something recorded.. but the quality is pretty bad.. (gif attached)

Seems like the example doesnt work with android version 7 onwards..

**Comment by banandelfiner** [comment]
You can't record from simulator. Although I believe one could make an extension to the package and make it record the device's screen.

**Comment by KlavierCat** [comment]
@ramneekhanda How did you manage? I couldn't get the video recording working for Android. I've set the `buildToolsVersion` to 25.0.3. I've added the permission in the manifest. In the end an mp4 file is indeed created but it is an empty file. The iOS video recording function works fine for me though. Any tip?

**Comment by KlavierCat** [comment]
Just solved it myself. So indeed as @banandelfiner said I could not make it work on an emulator. But when I run it on my old phone:
Android version: 6.0.1
System version: 24.216.12
The video recording function is working fine.

**Comment by rt2zz** [comment]
👍
