### ISSUE TITLE
camera.capture() not working on android 5.1

### ISSUE THREAD

**Issue by alainib** [lwansbrough/react-native-camera#775]
hello
i tryed this code on android 5.1 and did'nt work ( ok on android 7 )

 	  takePicture() {
		console.log("takePicture"); // logged
		this.camera.capture()
		  .then(data => {
			console.log("Picture",data); // not logged ! 
		  })
		  .catch(err => console.error(err));
	  }

my config :  
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-camera-roll-picker": "^1.1.9",

**Comment by cxjpxl** [comment]
how can you solute  this  in android 7

**Comment by karltaylor** [comment]
+1 for Android 7.0

**Comment by sibelius** [comment]
did you ask for camera permissions on android?

**Comment by karltaylor** [comment]
@sibelius Yep, just doesn't fire the promise :(

```javascript
Permissions.check('camera').then(response => console.log(response)); // -> authorized
```

**Comment by karltaylor** [comment]
@alainib You've closed this - did you find a solution?
