### ISSUE TITLE
Barcode scanning slow

### ISSUE THREAD

**Issue by LeoFidjeland** [lwansbrough/react-native-camera#78]
Hiya!

First of all, thanks for your great work! This is awesome!

I'm having some issues with the Barcode scanning being slow. Sometimes it takes like 15 seconds of the barcode being fully in focus before it gets read.

I put some breakpoints in didOutputMetadataObjects, and it seems like it's Apple code that is the problem.
I'm just wondering if anyone else is having the same issue? And if there is something I can do to speed it up.
I'm comparing with a few other iOS apps out there (like NeoReader) that scan the same code super fast.

**Comment by LeoFidjeland** [comment]
Maybe this is still valid...
https://blog.sabintsev.com/apples-native-ios-barcode-scanner-is-junk-83d2129bd017

**Comment by lwansbrough** [comment]
It's possible that those faster scanners use a custom library if that's true about the speed of the native barcode scanner. That's unfortunate. We're sticking to Apple's libraries for this module for simplicity. Let me know if you discover anything.

**Comment by LeoFidjeland** [comment]
Ok will do. My plan is to see if it works better with QR-codes than with Aztecs. Otherwise make a RN wrapper for a custom library. Currently my eyes are on https://github.com/TheLevelUp/ZXingObjC

**Comment by LeoFidjeland** [comment]
Yeay I switched to QR codes and the performance is much better! Seems like it was the Aztec code in particular that was crappy.

Thanks for for attention :)

**Comment by danna88** [comment]
i have the same issue in android! Can you tell me the way to solve this problem?

**Comment by zorosun** [comment]
I also have the same issue with old mobile phone, it seems that the phone is unable to correctly focus on the QR

**Comment by augusto-altman** [comment]
I have the same issue on Android!

**Comment by abdulrahman-khankan** [comment]
Same thing on Android, trying to read EAN-13 codes but it's too slow. With Expo's API demo app it's super fast and it's built on top of this :/ Not sure if I'm doing something wrong.

**Comment by MohsenKhosravinia** [comment]
you can use the below answer:

https://github.com/react-native-community/react-native-camera/issues/1002#issuecomment-566018391
