### ISSUE TITLE
Unable to read Code128 barcodes

### ISSUE THREAD

**Issue by ironars** [lwansbrough/react-native-camera#797]
I am using react native camera to read barcodes on iOS. I am unable to read the CODE128 barcode types. However, other formats seems to be working fine. Is there something I might be missing?

**Comment by connercms** [comment]
Did you find a fix for this? I am also able to scan other formats but code128 barcodes do not work

**Comment by Unforgiven-wanda** [comment]
Having the same issue, although all other barcode types work well.
This might warrant reopening this issue I think.
