### ISSUE TITLE
sample code in README produces error

### ISSUE THREAD

**Issue by eduedix** [lwansbrough/react-native-camera#8]
I get the following error in iOS simulator, when I try to run the sample code in README:

```
[RCTLog][tid:0x7f80b0519680][RCTConvert.m:843]>Exception thrown while attempting to set property 'camera' of 'RCTCamera' with value '1': *** Can't add a nil AVCaptureInput

[RCTLog][tid:0x7f80b0519680][RCTCameraManager.m:27]>RCTCamera does not have setter for `camera` property
```

Is this normal when the app is run in iOS simulator?

**Comment by lwansbrough** [comment]
Ah, yes I think that is to be expected. The simulator doesn't have a camera. That being said, I should add some checks to make sure the app isn't throwing errors/crashing in the simulator.

**Comment by booxood** [comment]
+1
