### ISSUE TITLE
RN47.0 has removed `createJSModules` method

### ISSUE THREAD

**Issue by lslvxy** [lwansbrough/react-native-camera#824]
RN47.0 change log [https://github.com/facebook/react-native/releases/tag/v0.47.0](https://github.com/facebook/react-native/releases/tag/v0.47.0)

**Comment by mikaello** [comment]
The fix for this is now in master: https://github.com/lwansbrough/react-native-camera/commit/02eb51d962c8b55ffd46f256d223aa41cd2df4a4 (PR #821)

**Comment by mo-solnet** [comment]
Is the fix for this going to be released on npm soon?

**Comment by JCMais** [comment]
@rt2zz when we can expect a new release?

**Comment by ptomasroos** [comment]
You can always use the git has if wanting to run later code available before the release is cut
https://docs.npmjs.com/files/package.json#repository
