### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by chendongcd** [lwansbrough/react-native-camera#827]
I downloaded the project,I want to run the example.But after I npm install in the example and run the example it always run error about the react-native-camera/index.js not  fount react.Can you tell me how to run the example in ios?
Thanks a lot

**Comment by skovhus** [comment]
@ptomasroos 

Having the same issue. Running `npm i && node node_modules/react-native/local-cli/cli.js start --reset-cache` inside the `Example` folder gives the following error:

```
transformed 388/398 (97%)(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 650): UnableToResolveError: Unable to resolve module react from /Users/kenneth/git/react-native-camera/index.js: Module does not exist in the module map or in these directories:
  /Users/kenneth/git/node_modules
,   /Users/kenneth/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```

I'm having the same issue in a local react-native module. Any suggestions on how you usually start the example app?

Using npm@5 and node@6.11.1
