### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by AlmogRnD** [lwansbrough/react-native-camera#837]
Is this project still alive over 300 issues and 50 pull request

**Comment by rt2zz** [comment]
its alive, and in need of contributors! We do our best to keep things stable - and generally it works for standard use cases.

**Comment by AlmogRnD** [comment]
@rt2zz there are 50 pull request that has not been merged kind of hard to get new contributors is no one is even bothering to merge the pull request when I see that I think why should I spend time working on the lib helping if no one can even merge the work
