### ISSUE TITLE
Visual shutter effect on iOS?

### ISSUE THREAD

**Issue by svenadlung** [lwansbrough/react-native-camera#840]
Is there any way to show a visual shutter effect (black or white flashing screen) while capturing a photo? I know there is a prop for `sound`on iOS, but anyways I don't see any visual feedback.

Regards.

**Comment by adjustit** [comment]
You'd need to utilise a thenable after `capture` to send a `state` update that had a custom overlay, probably using RN's `Animated` library. The logic flow would be capture -> set state to true -> conditionally show overlay on true state and set state to false. Shouldn't be too tricky to knock up.

**Comment by svenadlung** [comment]
Thank you! I was thinking about that way, but I wasn't sure if there is any prebuilt solution.
