### ISSUE TITLE
when i set the 'onBarCodeRead' prop will make me app exit.

### ISSUE THREAD

**Issue by DeFenceD** [lwansbrough/react-native-camera#853]
If I set 'onBarCodeRead' , when i first  time into scan it is OK, then i navigate to other view.
Now, I navigate into Scan view again, it will make me app exit.
I check the cause, when I set the props 'onBarCodeRead' can encounter this problem.

This is my camera and my navigation.
`<Camera ref='scan' style={css.preview}  onBarCodeRead={this.methods.scan}  aspect={Camera.constants.Aspect.fill}>`

Change view by this.
`navigation.navigate('Scan', {task: 'scanAuthCode'});`

My environment
`"react": "16.0.0-alpha.12"`
`"react-native": "^0.47.2"`
`"react-native-barcodescanner": "^3.1.1"`
`"react-navigation": "^1.0.0-beta.12"`

**Comment by kerwin1** [comment]
I have the same problem,Can anyone help me?

**Comment by DeFenceD** [comment]
I see you look like Chinese, so I write Chinese first, if you can't read then I support English.
关键时要手动从路由记录数组中将Scan这个视图从该数组删除。
你可以监听去路由变化，或者在你想要需要删除的时候。
这样做完之后，就可以debug闪退的问题。
