### ISSUE TITLE
How to access 'data' field after capturing photo

### ISSUE THREAD

**Issue by seandkim** [lwansbrough/react-native-camera#861]
The doc says that "data: Returns a base64-encoded string with the capture data (only returned with the deprecated Camera.constants.CaptureTarget.memory)"

So currently, simple photo capture method only returns path and mediaUri. How do we access base64-encoded string using these two values?

**Comment by adjustit** [comment]
There is no method within the library for doing that anymore; it was deprecated some versions back. You'd need to implement a pattern to do it yourself either in native code, or in native JS (through the [FileReader API](https://developer.mozilla.org/de/docs/Web/API/FileReader) would be the obvious choice, particularly the `readAsDataURL` method). 

All methods have downsides – unless you actually need the `base64` representation, I'd opt for just rendering the image from the provided `path` property.
