### ISSUE TITLE
How to identify local 2D code pictures, such as albums？

### ISSUE THREAD

**Issue by yellowJhon** [lwansbrough/react-native-camera#872]
The project can identify pictures captured by the camera, but I did not find the interface to identify the local image. 
How to solve it？ Or this feature is not supported yet?

**Comment by ptomasroos** [comment]
Give it a try with react-native-image-picker

**Comment by yellowJhon** [comment]
Finally, I decide to link APP to the native platform by developing iOS and Android.

**Comment by TrustTheBoy** [comment]
@yellowJhon Hello, how do you implement this function

**Comment by yellowJhon** [comment]
Yeah
I'm sorry that I can't paste my source code here for some reasons.
You can refer this link 
[Java Examples for com.google.zxing.RGBLuminanceSource
](https://www.javatips.net/api/com.google.zxing.rgbluminancesource)to get more details.

**Comment by TrustTheBoy** [comment]
@yellowJhon  Thank you very much, but it only works on Android. iOS?

**Comment by yellowJhon** [comment]
I am not familiar with the iOS development...

**Comment by TrustTheBoy** [comment]
Ok, thanks again for your help, I'm looking for it @yellowJhon
