### ISSUE TITLE
undefined is not an object (evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by ferminmoli** [lwansbrough/react-native-camera#877]
undefined is not an object (evaluating 'CameraManager.Aspect')

**Comment by lodi-g** [comment]
#748 
Don't open new issues that only slows down the process.

**Comment by SPATAN18** [comment]
Remove the app from your phone or emulator and then re-run react-native run-android or ios

**Comment by mashwinprdxn** [comment]
In case anyone's facing this issue on Android, please try the [gradle upgrade guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md). It worked for me.
