### ISSUE TITLE
Taking picture while in Emulator (iOS: OK, Android: KO)

### ISSUE THREAD

**Issue by btoueg** [lwansbrough/react-native-camera#879]
```
react-native@0.46.3
react-native-camera@0.8.0
```

When I'm using [Appetize.io](https://appetize.io/) or the emulator/simulator to demonstrate taking picture, iOS behave in a very friendly manner by mocking a picture. On the other hand, Android returns an empty image.

How can I achieve the same behavior on both platform?

Should I handle this in the app JS or in the react-native-camera Android module with a PR?

**Comment by ptomasroos** [comment]
We're not responsible for what a emulator might and might not do, rather just users out of the API's the platform provides. A bit out of the scope of issues. Some issues like genymotion provides polyfills. I dont expect us to provide special code to run in emulators
