### ISSUE TITLE
Camera crashes in Simulator 

### ISSUE THREAD

**Issue by bfwg** [lwansbrough/react-native-camera#89]
This issue is same as #71 
I think it is because I upgraded xCode to 7?
<img width="1128" alt="screen shot 2015-09-18 at 3 25 00 pm" src="https://cloud.githubusercontent.com/assets/12819525/9972467/86f1baaa-5e19-11e5-9867-7e2c885ce144.png">
<img width="1210" alt="screen shot 2015-09-18 at 3 25 12 pm" src="https://cloud.githubusercontent.com/assets/12819525/9972468/86f4dec4-5e19-11e5-93af-2fd1b4752b09.png">

**Comment by jtremback** [comment]
Is it really the same issue as #71? I fixed that a long time ago. #71 involved the camera crashing when you take a picture. Is this still the case for you?

**Comment by bfwg** [comment]
@lwansbrough 
No, It was when I open the project it will stop and show this error, somehow this problem went away. But in the simulator I can't open my camera, I will ask me weather I allow the app to access the camera, and after I click yes, I show nothing but a black background.
