### ISSUE TITLE
Get base64 encoded string

### ISSUE THREAD

**Issue by Stophface** [lwansbrough/react-native-camera#892]
I wonder how I get the `base64` encoded string. `captureTarget` can be set to `Camera.constants.CaptureTarget.memory` which should return the `base64` encoded string. Although it mentions that is deprecated, the docs say it returns the `base64` encoded string. 

> When using the deprecated memory output, the image binary is sent back as a base64-encoded string.

However, logging the data, returns me a link to a location:

```
    _takePhoto() {
        const options = {};
        this.camera.capture({ metadata: options })
            .then((data) => {
                console.log("photo data", data, data.path)
            })
            .catch(err => console.error(err))
    }
```

Is `base64` not supported anymore?

**Comment by augustolazaro** [comment]
I think base64 is at `data.data`

**Comment by sibelius** [comment]
@augustolazaro answer is correctly

**Comment by pacozaa** [comment]
@augustolazaro  @sibelius my `data.data` is `undefined`
