### ISSUE TITLE
Unable to resolve module merge

### ISSUE THREAD

**Issue by bfwg** [lwansbrough/react-native-camera#90]
<img width="1034" alt="screen shot 2015-09-18 at 10 18 02 pm" src="https://cloud.githubusercontent.com/assets/12819525/9974718/277b7f5e-5e53-11e5-8a67-24f1ef038573.png">
Is this normal?

**Comment by davidsims9t** [comment]
I'm having the same issue. The module worked prior to upgrading to IOS 9.

**Comment by lwansbrough** [comment]
Should be fixed in v0.3.4!
