### ISSUE TITLE
Crash on Android 4.4.4 every time

### ISSUE THREAD

**Issue by novellizator** [lwansbrough/react-native-camera#900]
Whenever we try to take a picture (in Samsung Galaxy S2), the whole app crashes.
Doesn't crash when we scan barcodes though.

**Comment by cloudsafe** [comment]
the same

**Comment by sahir** [comment]
can you Please provide crash logs.

**Comment by cloudsafe** [comment]
@sahir I found the reason.
Configure Apps with Over 64K Methods.
And I was configure error.
Now,I want display status bar ,when I use camera .
Do you have some ideas?

**Comment by novellizator** [comment]
Ok solved, https://github.com/lwansbrough/react-native-camera/issues/590 is the issue. On android I had to set up a larger heap.

**Comment by sahir** [comment]
@cloudsafe you can customize Camera view using **styles.overlay, styles.topOverlay** for example in my case I add Button and text in Camera View: https://github.com/sahir/react-native-barcode-reader

**Comment by cloudsafe** [comment]
@sahir sorry,I was said it wrong,I want hidden the status bar. now I finished .
set 
_viewFinder.setSystemUiVisibility(SYSTEM_UI_FLAG_FULLSCREEN);
in RCTCameraView.java
