### ISSUE TITLE
Documentation example crashes, needs more perms.

### ISSUE THREAD

**Issue by victorbadila** [lwansbrough/react-native-camera#906]
I tried the example in the documentation and the app seemed to crash when actually pressing the [take photo] button. The xCode log for this was:

> 2017-09-25 15:40:31.960516+0200 CameraTests[641:284445] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

Adding this permission in info.plist fixed the problem, I think this instruction should be added to README.md

**Comment by ptomasroos** [comment]
Fixed in #924
