### ISSUE TITLE
checkDeviceAuthorizationStatus is not work!!!

### ISSUE THREAD

**Issue by aspidvip** [lwansbrough/react-native-camera#922]
Hello!!!

if(Camera.checkDeviceAuthorizationStatus) {
  console.log('yes');
} else {
  console.log('no');
}

PLease Help

**Comment by SpidGiarz** [comment]
checkDeviceAuthorizationStatus is a promise method.

So your check would have to be something like:
```javascript
const someAsyncFunction = async () => {
 if(await Camera.checkDeviceAuthorizationStatus()) {
  console.log('yes');
 } else {
  console.log('no');
 }
}
```

**Comment by mfahad1** [comment]
@SpidGiarz what about if on false we want to ask user to allow camera access , so if some other time user want to redo the permission .

**Comment by SpidGiarz** [comment]
For Android leverage [PermissonsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html) or a third party module to determine the camera permission state and act accordingly:
- if denied; request again with the appropriate rationale.
- if never_ask_again; explain the situation and, optionally, provide a button to quickly take them to your app's settings page.

For iOS if false then justify the need for the permission while providing a button to transport them to your app's settings page.

**Comment by mfahad1** [comment]
@SpidGiarz thanks for a quick response , I am developing for IOS .. Is there really no way other then manually changing permission of the app ?

**Comment by SpidGiarz** [comment]
Sadly none, other than providing them a compelling reason to manually grant you that coveted permission.

**Comment by aspidvip** [comment]
componentDidMount(){
const someAsyncFunction = async () => {
 if(await Camera.checkDeviceAuthorizationStatus()) {
  console.log('yes');
 } else {
  console.log('no');
 }
}}
none work (((

**Comment by jgcmarins** [comment]
@aspidvip check this: https://github.com/lwansbrough/react-native-camera/blob/master/README.md#requirements

**Comment by aspidvip** [comment]
Camera.checkDeviceAuthorizationStatus()
    .then((result)=>{
      this.setState({
        accessFoto: result,
      });
})
this is work!!! thansk!!!

**Comment by aspidvip** [comment]
please close topic! thansk)
