### ISSUE TITLE
App Crashes in 11.0.1

### ISSUE THREAD

**Issue by vivekebics** [lwansbrough/react-native-camera#927]
unable to open the camera in ios 11.0.1.

**Comment by jgcmarins** [comment]
it's related to this: https://github.com/lwansbrough/react-native-camera/issues/923

**Comment by vivekebics** [comment]
Resolved Reference :   [#924](https://github.com/lwansbrough/react-native-camera/pull/924/commits/761aba3e14e92408387eace97a0261e260f6ac4e) 

I have just summarized the work solution. 

NSCameraUsageDescription

      <key>NSCameraUsageDescription</key>
      <string>$(PRODUCT_NAME).needs to save photos</string>

NSPhotoLibraryAddUsageDescription

     <key>NSPhotoLibraryAddUsageDescription</key>
     <string>$(PRODUCT_NAME).needs to take photos</string>

**Comment by ptomasroos** [comment]
See README.md
