### ISSUE TITLE
Doesn't work with react-native-webpack-server

### ISSUE THREAD

**Issue by sslash** [lwansbrough/react-native-camera#96]
I'm trying to use this with a project based on [https://github.com/mjohnston/react-native-webpack-server] (https://github.com/mjohnston/react-native-webpack-server), but I'm getting this error:

```ERROR in ./src/containers/Create/index.js
Module not found: Error: Cannot resolve module 'react-native-camera' in /Users/micgunnu/code/sap/routes/Routes-native/src/containers/Create
 @ ./src/containers/Create/index.js 48:13-43```

Any idea what might cause this?

**Comment by lwansbrough** [comment]
Can't say without a full stack trace or source code. The camera module works though so it's either a problem with the webpack server or your own code.

**Comment by sslash** [comment]
Think it has got something to do with the webpack server. Anyway, I went back to normal rn transformer for now, thanks :)

**Comment by pewallin** [comment]
@sslash - this is probably due to your Webpack configuration not transpiling react-native-camera in node_modules. A build step for this module would fix this. Or just add it to your webpack.config.js...

**Comment by thachp** [comment]
I am experiencing this problem.  How do you "add it to your webpack.config.js" ?
