### ISSUE TITLE
Need to be published on npm

### ISSUE THREAD

**Issue by klaytonfaria** [lwansbrough/react-native-camera#974]
https://github.com/lwansbrough/react-native-camera/blob/59a0b44c71c7b13601dfd34b43714bf8cbb198eb/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraPackage.java#L20

**Comment by koswarabilly** [comment]
anyway the code in this repository is also deprecated as shown here [RCTCameraPackage.java](https://github.com/lwansbrough/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraPackage.java)

**Comment by sibelius** [comment]
done
