### ISSUE TITLE
stop scan method?

### ISSUE THREAD

**Issue by yedeba** [lwansbrough/react-native-camera#98]
Hi, stop scan barcode method exists?
Thanks

**Comment by lwansbrough** [comment]
Unbind the event handler.

**Comment by GarimaMathur07** [comment]
@lwansbrough We receive multiple (~10x) same barcode in a single camera capture:  using bind and unbind listner approach reduces it for some time but it call again in 2-3 seconds. can you please tell me using code snippet

**Comment by danilovdev** [comment]
How to do that? 

> Unbind the event handler.

**Comment by yedeba** [comment]
Hi, I simplified it with simple var control.

const intoscan = false;
_onBarCodeRead(e) {
    if(intoscan==false){
        intoscan=true;
        ....

**Comment by efstathiosntonas** [comment]
@lwansbrough can you please share some code on how to do that?

**Comment by jgcmarins** [comment]
@efstathiosntonas pull requests are always welcome \o/
