### ISSUE TITLE
Camera is half transparent into an android modal

### ISSUE THREAD

**Issue by l1br3** [lwansbrough/react-native-camera#983]
I've got the `<Camera/>` component (right from exemple in readme) into a modal and it is half transparent. It means that I can see the modal content behind the camera view as if a white opacity of 0.5 was applied.  
This does not happen into a non-modal view.

I've found a workaround, I simply put a full height black background on the modal holder view when the modal is opened and then it works perfectly.

No rush, but very strange.

```
Android 8 (API26)
RN 0.48
react-native-camera 0.12.0
```

Code could look like that:
```javascript
<View>
  some visible content through the modal only in the camera view
  <Modal>
    <Camera>
      This view will make the modal half transparent and I can see the text which is before/outside the modal
    </Camera>
  </Modal>
</View>

```

![screenshot_1510694291](https://user-images.githubusercontent.com/3482025/32805513-f7ebd5b4-c989-11e7-8136-a9a9d2c5af6d.png)

**Comment by viacheslav-gotsuliak** [comment]
Having the same issue, 

@l1br3 Could you please explain how to make this black background to fix that transparency? I tried wrapping <Camera> to <View> with black backgroundColor but this doesn't help.

Thanks.

**Comment by l1br3** [comment]
@viacheslav-gotsuliak Simply apply a background on the background view, the one which is behind the modal. 
When the modal is open, there is a black overlay background on the view under the modal.

**Comment by vladimirnani** [comment]
**opacity: 0.9** did the trick for me otherwise camera couldnt get through

```
<View>
    <Modal>
        <View style={{ flex: 1, backgroundColor: "black", opacity: 0.9999 }}>
            <Camera style={{ flex: 1 }}>
            </Camera>
        </View>
    </Modal>
</View>
```

**Comment by viacheslav-gotsuliak** [comment]
There is no such transparency on real devices, so it's not so critical. (Tested on Android as of now, later will test on ios devices)

**Comment by vladimirnani** [comment]
@viacheslav-gotsuliak Thanks just tested and confirm no issue on real device.

**Comment by viacheslav-gotsuliak** [comment]
Tested on real iPhone, works fine, no transparency.

**Comment by l1br3** [comment]
Nice to ear ! I must admit that I didn't even gave it a try on real device !

**Comment by l1br3** [comment]
I close the issue as it's non blocking. Feel free to re open it if you think it worth it :)
