### ISSUE TITLE
Issue with requiring unknown module 'react-native-camera'

### ISSUE THREAD

**Issue by josiahbgrace** [lwansbrough/react-native-camera#99]
I'm trying to use the react-native-camera in a project and I keep running into this error:

```
Requiring unknown module "react-native-camera". If you are sure the module is there, try restarting the packager.
```

I've tried to debug with a clean build and run and clean installs of the package. Any help would be appreciated. I'm using version 0.3.6 with react-native version 0.11.4.

**Comment by viscasillas** [comment]
have you tried restarting Xcode or the packager itself?

**Comment by josiahbgrace** [comment]
Yes, I've tried both of those.

**Comment by lwansbrough** [comment]
I haven't looked into this yet so it could be a problem with the module (though I'd doubt they'd break something in a minor version change.) Maybe try clearing your Babel cache? (`rm ~/.babel.json`)

**Comment by josiahbgrace** [comment]
Hm... Yeah, that didn't fix the issue either. I'm working on other parts of the project now, but I'll circle back to this later and see if I can do some more digging to add some more concrete details to this issue.

**Comment by prathamesh-sonpatki** [comment]
I am also facing same issue with version 0.3.7 with react-native version 0.7.1.

**Comment by morenoh149** [comment]
experiencing the same on `0.3.7` react-native `0.11.0`

**Comment by lwansbrough** [comment]
@prathamesh-sonpatki Not supporting that many versions back of RN.

@morenoh149 Can you update the camera and verify that this is an issue still?

**Comment by amccloud** [comment]
@josiahbgrace @prathamesh-sonpatki  @morenoh149 are you using react-native-webpack-server?

**Comment by morenoh149** [comment]
@amccloud yes actually. `"react-native-webpack-server": "^0.7.1",`

**Comment by amccloud** [comment]
@morenoh149 It doesn't handle index.ios.js and index.android.js like you'd expect. You can import this way:

```js
import Camera from 'react-native-camera/index.ios';
```

**Comment by amccloud** [comment]
@lwansbrough You could probably close this as it is likely a `react-native-webpack-server` issue https://github.com/mjohnston/react-native-webpack-server/issues/96

**Comment by josiahbgrace** [comment]
I am not using the react-native-webpack-server, but the code suggested above 

    import Camera from 'react-native-camera/index.ios';

fixes the issue (with the example code in the readme).

**Comment by blacksunset** [comment]
@josiahbgrace 
```
import Camera from 'react-native-camera/index.ios';
```
i tried the code above but i got
SystaxError:Unexpected use of reserved word 'import'

**Comment by josiahbgrace** [comment]
I don't know what I was thinking when I copied that over.... My actual code is 

    var Camera = require('react-native-camera/index.ios');

https://github.com/josiahbgrace/ClothesMatcher/blob/master/CameraUtil.js

And checkout this file for base code.

**Comment by blacksunset** [comment]
@josiahbgrace Thank you, i have fixed the problem.
When i installed the  react-native-camera with command like this
```
npm  install react-native-camera@latest --save
```
the folder “react-native-camera” was created in mode_modules. i just copied the folder into /path/[project_name]/node_modules/  
then completed the steps from 2 - 6 in the readme
