### ISSUE TITLE
router-flux not showing the camera component

### ISSUE THREAD

**Issue by nestormejia98** [lwansbrough/react-native-camera#994]
###Version

react-native-router-flux v3.43
-react-native-camera v0.12
react-native v0.49.5
Expected behaviour

Open the camera when calling the component QrScanner

###Actual behaviour

Showing a blank screen, I was able to tell it was my component because i've conditioned my render with some state variables

###Steps to reproduce

1.new project, install router-flux and react-native camera
2.Create three components: Login, Menu and QrScanner
3. Routing:
from Login to Menu and from Menu to QrScanner

PS. I've tested rendering just the QrScanner component before installing router-flux and worked fine so I assume it's not an issue with the component.

**Comment by telmen** [comment]
how did u solve this?
